package com.intramirror.order.api.model;

import java.math.BigDecimal;
import java.util.Date;

public class OrderLogistics {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_logistics.order_logistics_id
     *
     * @mbggenerated
     */
    private Long orderLogisticsId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_logistics.shop_id
     *
     * @mbggenerated
     */
    private Long shopId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_logistics.order_id
     *
     * @mbggenerated
     */
    private Long orderId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_logistics.destination_type
     *
     * @mbggenerated
     */
    private Byte destinationType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_logistics.type
     *
     * @mbggenerated
     */
    private Byte type;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_logistics.ship_payer
     *
     * @mbggenerated
     */
    private Byte shipPayer;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_logistics.ship_fee
     *
     * @mbggenerated
     */
    private BigDecimal shipFee;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_logistics.fee
     *
     * @mbggenerated
     */
    private BigDecimal fee;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_logistics.deduct_fee
     *
     * @mbggenerated
     */
    private BigDecimal deductFee;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_logistics.remain_fee
     *
     * @mbggenerated
     */
    private BigDecimal remainFee;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_logistics.receive_fee
     *
     * @mbggenerated
     */
    private BigDecimal receiveFee;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_logistics.status
     *
     * @mbggenerated
     */
    private Byte status;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_logistics.logistics_id
     *
     * @mbggenerated
     */
    private Long logisticsId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_logistics.return_application_id
     *
     * @mbggenerated
     */
    private Long returnApplicationId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_logistics.created_at
     *
     * @mbggenerated
     */
    private Date createdAt;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_logistics.updated_at
     *
     * @mbggenerated
     */
    private Date updatedAt;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_logistics.enabled
     *
     * @mbggenerated
     */
    private Boolean enabled;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_logistics.is_ship_fee
     *
     * @mbggenerated
     */
    private Boolean isShipFee;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_logistics.remark
     *
     * @mbggenerated
     */
    private String remark;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_logistics.order_logistics_id
     *
     * @return the value of order_logistics.order_logistics_id
     *
     * @mbggenerated
     */
    public Long getOrderLogisticsId() {
        return orderLogisticsId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order_logistics.order_logistics_id
     *
     * @param orderLogisticsId the value for order_logistics.order_logistics_id
     *
     * @mbggenerated
     */
    public void setOrderLogisticsId(Long orderLogisticsId) {
        this.orderLogisticsId = orderLogisticsId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_logistics.shop_id
     *
     * @return the value of order_logistics.shop_id
     *
     * @mbggenerated
     */
    public Long getShopId() {
        return shopId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order_logistics.shop_id
     *
     * @param shopId the value for order_logistics.shop_id
     *
     * @mbggenerated
     */
    public void setShopId(Long shopId) {
        this.shopId = shopId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_logistics.order_id
     *
     * @return the value of order_logistics.order_id
     *
     * @mbggenerated
     */
    public Long getOrderId() {
        return orderId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order_logistics.order_id
     *
     * @param orderId the value for order_logistics.order_id
     *
     * @mbggenerated
     */
    public void setOrderId(Long orderId) {
        this.orderId = orderId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_logistics.destination_type
     *
     * @return the value of order_logistics.destination_type
     *
     * @mbggenerated
     */
    public Byte getDestinationType() {
        return destinationType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order_logistics.destination_type
     *
     * @param destinationType the value for order_logistics.destination_type
     *
     * @mbggenerated
     */
    public void setDestinationType(Byte destinationType) {
        this.destinationType = destinationType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_logistics.type
     *
     * @return the value of order_logistics.type
     *
     * @mbggenerated
     */
    public Byte getType() {
        return type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order_logistics.type
     *
     * @param type the value for order_logistics.type
     *
     * @mbggenerated
     */
    public void setType(Byte type) {
        this.type = type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_logistics.ship_payer
     *
     * @return the value of order_logistics.ship_payer
     *
     * @mbggenerated
     */
    public Byte getShipPayer() {
        return shipPayer;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order_logistics.ship_payer
     *
     * @param shipPayer the value for order_logistics.ship_payer
     *
     * @mbggenerated
     */
    public void setShipPayer(Byte shipPayer) {
        this.shipPayer = shipPayer;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_logistics.ship_fee
     *
     * @return the value of order_logistics.ship_fee
     *
     * @mbggenerated
     */
    public BigDecimal getShipFee() {
        return shipFee;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order_logistics.ship_fee
     *
     * @param shipFee the value for order_logistics.ship_fee
     *
     * @mbggenerated
     */
    public void setShipFee(BigDecimal shipFee) {
        this.shipFee = shipFee;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_logistics.fee
     *
     * @return the value of order_logistics.fee
     *
     * @mbggenerated
     */
    public BigDecimal getFee() {
        return fee;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order_logistics.fee
     *
     * @param fee the value for order_logistics.fee
     *
     * @mbggenerated
     */
    public void setFee(BigDecimal fee) {
        this.fee = fee;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_logistics.deduct_fee
     *
     * @return the value of order_logistics.deduct_fee
     *
     * @mbggenerated
     */
    public BigDecimal getDeductFee() {
        return deductFee;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order_logistics.deduct_fee
     *
     * @param deductFee the value for order_logistics.deduct_fee
     *
     * @mbggenerated
     */
    public void setDeductFee(BigDecimal deductFee) {
        this.deductFee = deductFee;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_logistics.remain_fee
     *
     * @return the value of order_logistics.remain_fee
     *
     * @mbggenerated
     */
    public BigDecimal getRemainFee() {
        return remainFee;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order_logistics.remain_fee
     *
     * @param remainFee the value for order_logistics.remain_fee
     *
     * @mbggenerated
     */
    public void setRemainFee(BigDecimal remainFee) {
        this.remainFee = remainFee;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_logistics.receive_fee
     *
     * @return the value of order_logistics.receive_fee
     *
     * @mbggenerated
     */
    public BigDecimal getReceiveFee() {
        return receiveFee;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order_logistics.receive_fee
     *
     * @param receiveFee the value for order_logistics.receive_fee
     *
     * @mbggenerated
     */
    public void setReceiveFee(BigDecimal receiveFee) {
        this.receiveFee = receiveFee;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_logistics.status
     *
     * @return the value of order_logistics.status
     *
     * @mbggenerated
     */
    public Byte getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order_logistics.status
     *
     * @param status the value for order_logistics.status
     *
     * @mbggenerated
     */
    public void setStatus(Byte status) {
        this.status = status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_logistics.logistics_id
     *
     * @return the value of order_logistics.logistics_id
     *
     * @mbggenerated
     */
    public Long getLogisticsId() {
        return logisticsId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order_logistics.logistics_id
     *
     * @param logisticsId the value for order_logistics.logistics_id
     *
     * @mbggenerated
     */
    public void setLogisticsId(Long logisticsId) {
        this.logisticsId = logisticsId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_logistics.return_application_id
     *
     * @return the value of order_logistics.return_application_id
     *
     * @mbggenerated
     */
    public Long getReturnApplicationId() {
        return returnApplicationId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order_logistics.return_application_id
     *
     * @param returnApplicationId the value for order_logistics.return_application_id
     *
     * @mbggenerated
     */
    public void setReturnApplicationId(Long returnApplicationId) {
        this.returnApplicationId = returnApplicationId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_logistics.created_at
     *
     * @return the value of order_logistics.created_at
     *
     * @mbggenerated
     */
    public Date getCreatedAt() {
        return createdAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order_logistics.created_at
     *
     * @param createdAt the value for order_logistics.created_at
     *
     * @mbggenerated
     */
    public void setCreatedAt(Date createdAt) {
        this.createdAt = createdAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_logistics.updated_at
     *
     * @return the value of order_logistics.updated_at
     *
     * @mbggenerated
     */
    public Date getUpdatedAt() {
        return updatedAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order_logistics.updated_at
     *
     * @param updatedAt the value for order_logistics.updated_at
     *
     * @mbggenerated
     */
    public void setUpdatedAt(Date updatedAt) {
        this.updatedAt = updatedAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_logistics.enabled
     *
     * @return the value of order_logistics.enabled
     *
     * @mbggenerated
     */
    public Boolean getEnabled() {
        return enabled;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order_logistics.enabled
     *
     * @param enabled the value for order_logistics.enabled
     *
     * @mbggenerated
     */
    public void setEnabled(Boolean enabled) {
        this.enabled = enabled;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_logistics.is_ship_fee
     *
     * @return the value of order_logistics.is_ship_fee
     *
     * @mbggenerated
     */
    public Boolean getIsShipFee() {
        return isShipFee;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order_logistics.is_ship_fee
     *
     * @param isShipFee the value for order_logistics.is_ship_fee
     *
     * @mbggenerated
     */
    public void setIsShipFee(Boolean isShipFee) {
        this.isShipFee = isShipFee;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_logistics.remark
     *
     * @return the value of order_logistics.remark
     *
     * @mbggenerated
     */
    public String getRemark() {
        return remark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order_logistics.remark
     *
     * @param remark the value for order_logistics.remark
     *
     * @mbggenerated
     */
    public void setRemark(String remark) {
        this.remark = remark == null ? null : remark.trim();
    }
}