package com.intramirror.order.api.model;

import java.math.BigDecimal;
import java.util.Date;

public class Order {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order.order_id
     *
     * @mbggenerated
     */
    private Long orderId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order.order_num
     *
     * @mbggenerated
     */
    private String orderNum;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order.user_id
     *
     * @mbggenerated
     */
    private Long userId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order.fee
     *
     * @mbggenerated
     */
    private BigDecimal fee;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order.coupon
     *
     * @mbggenerated
     */
    private String coupon;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order.coupon_fee
     *
     * @mbggenerated
     */
    private BigDecimal couponFee;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order.discount
     *
     * @mbggenerated
     */
    private Integer discount;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order.discount_fee
     *
     * @mbggenerated
     */
    private BigDecimal discountFee;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order.ship_fee
     *
     * @mbggenerated
     */
    private BigDecimal shipFee;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order.pay_fee
     *
     * @mbggenerated
     */
    private BigDecimal payFee;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order.pay_way
     *
     * @mbggenerated
     */
    private Byte payWay;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order.online_payment_id
     *
     * @mbggenerated
     */
    private Long onlinePaymentId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order.confirmed_at
     *
     * @mbggenerated
     */
    private Date confirmedAt;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order.status
     *
     * @mbggenerated
     */
    private Integer status;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order.cancel_type
     *
     * @mbggenerated
     */
    private Byte cancelType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order.created_at
     *
     * @mbggenerated
     */
    private Date createdAt;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order.updated_at
     *
     * @mbggenerated
     */
    private Date updatedAt;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order.enabled
     *
     * @mbggenerated
     */
    private Boolean enabled;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order.tax_fee
     *
     * @mbggenerated
     */
    private BigDecimal taxFee;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order.current_rate
     *
     * @mbggenerated
     */
    private BigDecimal currentRate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order.total_sale_price_rmb
     *
     * @mbggenerated
     */
    private BigDecimal totalSalePriceRmb;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order.total_shipping_fee_rmb
     *
     * @mbggenerated
     */
    private BigDecimal totalShippingFeeRmb;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order.total_tax_rmb
     *
     * @mbggenerated
     */
    private BigDecimal totalTaxRmb;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order.total_rmb
     *
     * @mbggenerated
     */
    private String totalRmb;


    private String remainingRmb;
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order.wechat
     *
     * @mbggenerated
     */
    private String wechat;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order.contact_phone
     *
     * @mbggenerated
     */
    private String contactPhone;


    private String buyerName;
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order.area_code
     *
     * @mbggenerated
     */
    private String areaCode;

    private Long channelId;

    public Long getChannelId() {
        return channelId;
    }

    public void setChannelId(Long channelId) {
        this.channelId = channelId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order.order_id
     *
     * @return the value of order.order_id
     * @mbggenerated
     */
    public Long getOrderId() {
        return orderId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order.order_id
     *
     * @param orderId the value for order.order_id
     * @mbggenerated
     */
    public void setOrderId(Long orderId) {
        this.orderId = orderId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order.order_num
     *
     * @return the value of order.order_num
     * @mbggenerated
     */
    public String getOrderNum() {
        return orderNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order.order_num
     *
     * @param orderNum the value for order.order_num
     * @mbggenerated
     */
    public void setOrderNum(String orderNum) {
        this.orderNum = orderNum == null ? null : orderNum.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order.user_id
     *
     * @return the value of order.user_id
     * @mbggenerated
     */
    public Long getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order.user_id
     *
     * @param userId the value for order.user_id
     * @mbggenerated
     */
    public void setUserId(Long userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order.fee
     *
     * @return the value of order.fee
     * @mbggenerated
     */
    public BigDecimal getFee() {
        return fee;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order.fee
     *
     * @param fee the value for order.fee
     * @mbggenerated
     */
    public void setFee(BigDecimal fee) {
        this.fee = fee;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order.coupon
     *
     * @return the value of order.coupon
     * @mbggenerated
     */
    public String getCoupon() {
        return coupon;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order.coupon
     *
     * @param coupon the value for order.coupon
     * @mbggenerated
     */
    public void setCoupon(String coupon) {
        this.coupon = coupon == null ? null : coupon.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order.coupon_fee
     *
     * @return the value of order.coupon_fee
     * @mbggenerated
     */
    public BigDecimal getCouponFee() {
        return couponFee;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order.coupon_fee
     *
     * @param couponFee the value for order.coupon_fee
     * @mbggenerated
     */
    public void setCouponFee(BigDecimal couponFee) {
        this.couponFee = couponFee;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order.discount
     *
     * @return the value of order.discount
     * @mbggenerated
     */
    public Integer getDiscount() {
        return discount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order.discount
     *
     * @param discount the value for order.discount
     * @mbggenerated
     */
    public void setDiscount(Integer discount) {
        this.discount = discount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order.discount_fee
     *
     * @return the value of order.discount_fee
     * @mbggenerated
     */
    public BigDecimal getDiscountFee() {
        return discountFee;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order.discount_fee
     *
     * @param discountFee the value for order.discount_fee
     * @mbggenerated
     */
    public void setDiscountFee(BigDecimal discountFee) {
        this.discountFee = discountFee;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order.ship_fee
     *
     * @return the value of order.ship_fee
     * @mbggenerated
     */
    public BigDecimal getShipFee() {
        return shipFee;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order.ship_fee
     *
     * @param shipFee the value for order.ship_fee
     * @mbggenerated
     */
    public void setShipFee(BigDecimal shipFee) {
        this.shipFee = shipFee;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order.pay_fee
     *
     * @return the value of order.pay_fee
     * @mbggenerated
     */
    public BigDecimal getPayFee() {
        return payFee;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order.pay_fee
     *
     * @param payFee the value for order.pay_fee
     * @mbggenerated
     */
    public void setPayFee(BigDecimal payFee) {
        this.payFee = payFee;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order.pay_way
     *
     * @return the value of order.pay_way
     * @mbggenerated
     */
    public Byte getPayWay() {
        return payWay;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order.pay_way
     *
     * @param payWay the value for order.pay_way
     * @mbggenerated
     */
    public void setPayWay(Byte payWay) {
        this.payWay = payWay;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order.online_payment_id
     *
     * @return the value of order.online_payment_id
     * @mbggenerated
     */
    public Long getOnlinePaymentId() {
        return onlinePaymentId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order.online_payment_id
     *
     * @param onlinePaymentId the value for order.online_payment_id
     * @mbggenerated
     */
    public void setOnlinePaymentId(Long onlinePaymentId) {
        this.onlinePaymentId = onlinePaymentId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order.confirmed_at
     *
     * @return the value of order.confirmed_at
     * @mbggenerated
     */
    public Date getConfirmedAt() {
        return confirmedAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order.confirmed_at
     *
     * @param confirmedAt the value for order.confirmed_at
     * @mbggenerated
     */
    public void setConfirmedAt(Date confirmedAt) {
        this.confirmedAt = confirmedAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order.status
     *
     * @return the value of order.status
     * @mbggenerated
     */
    public Integer getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order.status
     *
     * @param status the value for order.status
     * @mbggenerated
     */
    public void setStatus(Integer status) {
        this.status = status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order.cancel_type
     *
     * @return the value of order.cancel_type
     * @mbggenerated
     */
    public Byte getCancelType() {
        return cancelType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order.cancel_type
     *
     * @param cancelType the value for order.cancel_type
     * @mbggenerated
     */
    public void setCancelType(Byte cancelType) {
        this.cancelType = cancelType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order.created_at
     *
     * @return the value of order.created_at
     * @mbggenerated
     */
    public Date getCreatedAt() {
        return createdAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order.created_at
     *
     * @param createdAt the value for order.created_at
     * @mbggenerated
     */
    public void setCreatedAt(Date createdAt) {
        this.createdAt = createdAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order.updated_at
     *
     * @return the value of order.updated_at
     * @mbggenerated
     */
    public Date getUpdatedAt() {
        return updatedAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order.updated_at
     *
     * @param updatedAt the value for order.updated_at
     * @mbggenerated
     */
    public void setUpdatedAt(Date updatedAt) {
        this.updatedAt = updatedAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order.enabled
     *
     * @return the value of order.enabled
     * @mbggenerated
     */
    public Boolean getEnabled() {
        return enabled;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order.enabled
     *
     * @param enabled the value for order.enabled
     * @mbggenerated
     */
    public void setEnabled(Boolean enabled) {
        this.enabled = enabled;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order.tax_fee
     *
     * @return the value of order.tax_fee
     * @mbggenerated
     */
    public BigDecimal getTaxFee() {
        return taxFee;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order.tax_fee
     *
     * @param taxFee the value for order.tax_fee
     * @mbggenerated
     */
    public void setTaxFee(BigDecimal taxFee) {
        this.taxFee = taxFee;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order.current_rate
     *
     * @return the value of order.current_rate
     * @mbggenerated
     */
    public BigDecimal getCurrentRate() {
        return currentRate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order.current_rate
     *
     * @param currentRate the value for order.current_rate
     * @mbggenerated
     */
    public void setCurrentRate(BigDecimal currentRate) {
        this.currentRate = currentRate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order.total_sale_price_rmb
     *
     * @return the value of order.total_sale_price_rmb
     * @mbggenerated
     */
    public BigDecimal getTotalSalePriceRmb() {
        return totalSalePriceRmb;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order.total_sale_price_rmb
     *
     * @param totalSalePriceRmb the value for order.total_sale_price_rmb
     * @mbggenerated
     */
    public void setTotalSalePriceRmb(BigDecimal totalSalePriceRmb) {
        this.totalSalePriceRmb = totalSalePriceRmb;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order.total_shipping_fee_rmb
     *
     * @return the value of order.total_shipping_fee_rmb
     * @mbggenerated
     */
    public BigDecimal getTotalShippingFeeRmb() {
        return totalShippingFeeRmb;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order.total_shipping_fee_rmb
     *
     * @param totalShippingFeeRmb the value for order.total_shipping_fee_rmb
     * @mbggenerated
     */
    public void setTotalShippingFeeRmb(BigDecimal totalShippingFeeRmb) {
        this.totalShippingFeeRmb = totalShippingFeeRmb;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order.total_tax_rmb
     *
     * @return the value of order.total_tax_rmb
     * @mbggenerated
     */
    public BigDecimal getTotalTaxRmb() {
        return totalTaxRmb;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order.total_tax_rmb
     *
     * @param totalTaxRmb the value for order.total_tax_rmb
     * @mbggenerated
     */
    public void setTotalTaxRmb(BigDecimal totalTaxRmb) {
        this.totalTaxRmb = totalTaxRmb;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order.total_rmb
     *
     * @return the value of order.total_rmb
     * @mbggenerated
     */
    public String getTotalRmb() {
        return totalRmb;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order.total_rmb
     *
     * @param totalRmb the value for order.total_rmb
     * @mbggenerated
     */
    public void setTotalRmb(String totalRmb) {
        this.totalRmb = totalRmb == null ? null : totalRmb.trim();
    }


    public String getRemainingRmb() {
        return remainingRmb;
    }

    public void setRemainingRmb(String remainingRmb) {
        this.remainingRmb = remainingRmb;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order.wechat
     *
     * @return the value of order.wechat
     * @mbggenerated
     */
    public String getWechat() {
        return wechat;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order.wechat
     *
     * @param wechat the value for order.wechat
     * @mbggenerated
     */
    public void setWechat(String wechat) {
        this.wechat = wechat == null ? null : wechat.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order.contact_phone
     *
     * @return the value of order.contact_phone
     * @mbggenerated
     */
    public String getContactPhone() {
        return contactPhone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order.contact_phone
     *
     * @param contactPhone the value for order.contact_phone
     * @mbggenerated
     */
    public void setContactPhone(String contactPhone) {
        this.contactPhone = contactPhone == null ? null : contactPhone.trim();
    }

    public String getBuyerName() {
        return buyerName;
    }

    public void setBuyerName(String buyerName) {
        this.buyerName = buyerName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order.area_code
     *
     * @return the value of order.area_code
     * @mbggenerated
     */
    public String getAreaCode() {
        return areaCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order.area_code
     *
     * @param areaCode the value for order.area_code
     * @mbggenerated
     */
    public void setAreaCode(String areaCode) {
        this.areaCode = areaCode == null ? null : areaCode.trim();
    }
}