package com.intramirror.order.api.model;

import java.util.ArrayList;
import java.util.Date;
import java.util.List;

public class ThirdWarehouseExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table third_warehouse
     *
     * @mbg.generated
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table third_warehouse
     *
     * @mbg.generated
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table third_warehouse
     *
     * @mbg.generated
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table third_warehouse
     *
     * @mbg.generated
     */
    public ThirdWarehouseExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table third_warehouse
     *
     * @mbg.generated
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table third_warehouse
     *
     * @mbg.generated
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table third_warehouse
     *
     * @mbg.generated
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table third_warehouse
     *
     * @mbg.generated
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table third_warehouse
     *
     * @mbg.generated
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table third_warehouse
     *
     * @mbg.generated
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table third_warehouse
     *
     * @mbg.generated
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table third_warehouse
     *
     * @mbg.generated
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table third_warehouse
     *
     * @mbg.generated
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table third_warehouse
     *
     * @mbg.generated
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table third_warehouse
     *
     * @mbg.generated
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andIdIsNull() {
            addCriterion("id is null");
            return (Criteria) this;
        }

        public Criteria andIdIsNotNull() {
            addCriterion("id is not null");
            return (Criteria) this;
        }

        public Criteria andIdEqualTo(Long value) {
            addCriterion("id =", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotEqualTo(Long value) {
            addCriterion("id <>", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThan(Long value) {
            addCriterion("id >", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThanOrEqualTo(Long value) {
            addCriterion("id >=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThan(Long value) {
            addCriterion("id <", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThanOrEqualTo(Long value) {
            addCriterion("id <=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdIn(List<Long> values) {
            addCriterion("id in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotIn(List<Long> values) {
            addCriterion("id not in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdBetween(Long value1, Long value2) {
            addCriterion("id between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotBetween(Long value1, Long value2) {
            addCriterion("id not between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andOverseaShipmentNoIsNull() {
            addCriterion("oversea_shipment_no is null");
            return (Criteria) this;
        }

        public Criteria andOverseaShipmentNoIsNotNull() {
            addCriterion("oversea_shipment_no is not null");
            return (Criteria) this;
        }

        public Criteria andOverseaShipmentNoEqualTo(String value) {
            addCriterion("oversea_shipment_no =", value, "overseaShipmentNo");
            return (Criteria) this;
        }

        public Criteria andOverseaShipmentNoNotEqualTo(String value) {
            addCriterion("oversea_shipment_no <>", value, "overseaShipmentNo");
            return (Criteria) this;
        }

        public Criteria andOverseaShipmentNoGreaterThan(String value) {
            addCriterion("oversea_shipment_no >", value, "overseaShipmentNo");
            return (Criteria) this;
        }

        public Criteria andOverseaShipmentNoGreaterThanOrEqualTo(String value) {
            addCriterion("oversea_shipment_no >=", value, "overseaShipmentNo");
            return (Criteria) this;
        }

        public Criteria andOverseaShipmentNoLessThan(String value) {
            addCriterion("oversea_shipment_no <", value, "overseaShipmentNo");
            return (Criteria) this;
        }

        public Criteria andOverseaShipmentNoLessThanOrEqualTo(String value) {
            addCriterion("oversea_shipment_no <=", value, "overseaShipmentNo");
            return (Criteria) this;
        }

        public Criteria andOverseaShipmentNoLike(String value) {
            addCriterion("oversea_shipment_no like", value, "overseaShipmentNo");
            return (Criteria) this;
        }

        public Criteria andOverseaShipmentNoNotLike(String value) {
            addCriterion("oversea_shipment_no not like", value, "overseaShipmentNo");
            return (Criteria) this;
        }

        public Criteria andOverseaShipmentNoIn(List<String> values) {
            addCriterion("oversea_shipment_no in", values, "overseaShipmentNo");
            return (Criteria) this;
        }

        public Criteria andOverseaShipmentNoNotIn(List<String> values) {
            addCriterion("oversea_shipment_no not in", values, "overseaShipmentNo");
            return (Criteria) this;
        }

        public Criteria andOverseaShipmentNoBetween(String value1, String value2) {
            addCriterion("oversea_shipment_no between", value1, value2, "overseaShipmentNo");
            return (Criteria) this;
        }

        public Criteria andOverseaShipmentNoNotBetween(String value1, String value2) {
            addCriterion("oversea_shipment_no not between", value1, value2, "overseaShipmentNo");
            return (Criteria) this;
        }

        public Criteria andOverseaShipmentShipTimeIsNull() {
            addCriterion("oversea_shipment_ship_time is null");
            return (Criteria) this;
        }

        public Criteria andOverseaShipmentShipTimeIsNotNull() {
            addCriterion("oversea_shipment_ship_time is not null");
            return (Criteria) this;
        }

        public Criteria andOverseaShipmentShipTimeEqualTo(Date value) {
            addCriterion("oversea_shipment_ship_time =", value, "overseaShipmentShipTime");
            return (Criteria) this;
        }

        public Criteria andOverseaShipmentShipTimeNotEqualTo(Date value) {
            addCriterion("oversea_shipment_ship_time <>", value, "overseaShipmentShipTime");
            return (Criteria) this;
        }

        public Criteria andOverseaShipmentShipTimeGreaterThan(Date value) {
            addCriterion("oversea_shipment_ship_time >", value, "overseaShipmentShipTime");
            return (Criteria) this;
        }

        public Criteria andOverseaShipmentShipTimeGreaterThanOrEqualTo(Date value) {
            addCriterion("oversea_shipment_ship_time >=", value, "overseaShipmentShipTime");
            return (Criteria) this;
        }

        public Criteria andOverseaShipmentShipTimeLessThan(Date value) {
            addCriterion("oversea_shipment_ship_time <", value, "overseaShipmentShipTime");
            return (Criteria) this;
        }

        public Criteria andOverseaShipmentShipTimeLessThanOrEqualTo(Date value) {
            addCriterion("oversea_shipment_ship_time <=", value, "overseaShipmentShipTime");
            return (Criteria) this;
        }

        public Criteria andOverseaShipmentShipTimeIn(List<Date> values) {
            addCriterion("oversea_shipment_ship_time in", values, "overseaShipmentShipTime");
            return (Criteria) this;
        }

        public Criteria andOverseaShipmentShipTimeNotIn(List<Date> values) {
            addCriterion("oversea_shipment_ship_time not in", values, "overseaShipmentShipTime");
            return (Criteria) this;
        }

        public Criteria andOverseaShipmentShipTimeBetween(Date value1, Date value2) {
            addCriterion("oversea_shipment_ship_time between", value1, value2, "overseaShipmentShipTime");
            return (Criteria) this;
        }

        public Criteria andOverseaShipmentShipTimeNotBetween(Date value1, Date value2) {
            addCriterion("oversea_shipment_ship_time not between", value1, value2, "overseaShipmentShipTime");
            return (Criteria) this;
        }

        public Criteria andAwbNoIsNull() {
            addCriterion("awb_no is null");
            return (Criteria) this;
        }

        public Criteria andAwbNoIsNotNull() {
            addCriterion("awb_no is not null");
            return (Criteria) this;
        }

        public Criteria andAwbNoEqualTo(String value) {
            addCriterion("awb_no =", value, "awbNo");
            return (Criteria) this;
        }

        public Criteria andAwbNoNotEqualTo(String value) {
            addCriterion("awb_no <>", value, "awbNo");
            return (Criteria) this;
        }

        public Criteria andAwbNoGreaterThan(String value) {
            addCriterion("awb_no >", value, "awbNo");
            return (Criteria) this;
        }

        public Criteria andAwbNoGreaterThanOrEqualTo(String value) {
            addCriterion("awb_no >=", value, "awbNo");
            return (Criteria) this;
        }

        public Criteria andAwbNoLessThan(String value) {
            addCriterion("awb_no <", value, "awbNo");
            return (Criteria) this;
        }

        public Criteria andAwbNoLessThanOrEqualTo(String value) {
            addCriterion("awb_no <=", value, "awbNo");
            return (Criteria) this;
        }

        public Criteria andAwbNoLike(String value) {
            addCriterion("awb_no like", value, "awbNo");
            return (Criteria) this;
        }

        public Criteria andAwbNoNotLike(String value) {
            addCriterion("awb_no not like", value, "awbNo");
            return (Criteria) this;
        }

        public Criteria andAwbNoIn(List<String> values) {
            addCriterion("awb_no in", values, "awbNo");
            return (Criteria) this;
        }

        public Criteria andAwbNoNotIn(List<String> values) {
            addCriterion("awb_no not in", values, "awbNo");
            return (Criteria) this;
        }

        public Criteria andAwbNoBetween(String value1, String value2) {
            addCriterion("awb_no between", value1, value2, "awbNo");
            return (Criteria) this;
        }

        public Criteria andAwbNoNotBetween(String value1, String value2) {
            addCriterion("awb_no not between", value1, value2, "awbNo");
            return (Criteria) this;
        }

        public Criteria andOrderLineNumIsNull() {
            addCriterion("order_line_num is null");
            return (Criteria) this;
        }

        public Criteria andOrderLineNumIsNotNull() {
            addCriterion("order_line_num is not null");
            return (Criteria) this;
        }

        public Criteria andOrderLineNumEqualTo(String value) {
            addCriterion("order_line_num =", value, "orderLineNum");
            return (Criteria) this;
        }

        public Criteria andOrderLineNumNotEqualTo(String value) {
            addCriterion("order_line_num <>", value, "orderLineNum");
            return (Criteria) this;
        }

        public Criteria andOrderLineNumGreaterThan(String value) {
            addCriterion("order_line_num >", value, "orderLineNum");
            return (Criteria) this;
        }

        public Criteria andOrderLineNumGreaterThanOrEqualTo(String value) {
            addCriterion("order_line_num >=", value, "orderLineNum");
            return (Criteria) this;
        }

        public Criteria andOrderLineNumLessThan(String value) {
            addCriterion("order_line_num <", value, "orderLineNum");
            return (Criteria) this;
        }

        public Criteria andOrderLineNumLessThanOrEqualTo(String value) {
            addCriterion("order_line_num <=", value, "orderLineNum");
            return (Criteria) this;
        }

        public Criteria andOrderLineNumLike(String value) {
            addCriterion("order_line_num like", value, "orderLineNum");
            return (Criteria) this;
        }

        public Criteria andOrderLineNumNotLike(String value) {
            addCriterion("order_line_num not like", value, "orderLineNum");
            return (Criteria) this;
        }

        public Criteria andOrderLineNumIn(List<String> values) {
            addCriterion("order_line_num in", values, "orderLineNum");
            return (Criteria) this;
        }

        public Criteria andOrderLineNumNotIn(List<String> values) {
            addCriterion("order_line_num not in", values, "orderLineNum");
            return (Criteria) this;
        }

        public Criteria andOrderLineNumBetween(String value1, String value2) {
            addCriterion("order_line_num between", value1, value2, "orderLineNum");
            return (Criteria) this;
        }

        public Criteria andOrderLineNumNotBetween(String value1, String value2) {
            addCriterion("order_line_num not between", value1, value2, "orderLineNum");
            return (Criteria) this;
        }

        public Criteria andOrderImageIsNull() {
            addCriterion("order_image is null");
            return (Criteria) this;
        }

        public Criteria andOrderImageIsNotNull() {
            addCriterion("order_image is not null");
            return (Criteria) this;
        }

        public Criteria andOrderImageEqualTo(String value) {
            addCriterion("order_image =", value, "orderImage");
            return (Criteria) this;
        }

        public Criteria andOrderImageNotEqualTo(String value) {
            addCriterion("order_image <>", value, "orderImage");
            return (Criteria) this;
        }

        public Criteria andOrderImageGreaterThan(String value) {
            addCriterion("order_image >", value, "orderImage");
            return (Criteria) this;
        }

        public Criteria andOrderImageGreaterThanOrEqualTo(String value) {
            addCriterion("order_image >=", value, "orderImage");
            return (Criteria) this;
        }

        public Criteria andOrderImageLessThan(String value) {
            addCriterion("order_image <", value, "orderImage");
            return (Criteria) this;
        }

        public Criteria andOrderImageLessThanOrEqualTo(String value) {
            addCriterion("order_image <=", value, "orderImage");
            return (Criteria) this;
        }

        public Criteria andOrderImageLike(String value) {
            addCriterion("order_image like", value, "orderImage");
            return (Criteria) this;
        }

        public Criteria andOrderImageNotLike(String value) {
            addCriterion("order_image not like", value, "orderImage");
            return (Criteria) this;
        }

        public Criteria andOrderImageIn(List<String> values) {
            addCriterion("order_image in", values, "orderImage");
            return (Criteria) this;
        }

        public Criteria andOrderImageNotIn(List<String> values) {
            addCriterion("order_image not in", values, "orderImage");
            return (Criteria) this;
        }

        public Criteria andOrderImageBetween(String value1, String value2) {
            addCriterion("order_image between", value1, value2, "orderImage");
            return (Criteria) this;
        }

        public Criteria andOrderImageNotBetween(String value1, String value2) {
            addCriterion("order_image not between", value1, value2, "orderImage");
            return (Criteria) this;
        }

        public Criteria andSortingTypeIsNull() {
            addCriterion("sorting_type is null");
            return (Criteria) this;
        }

        public Criteria andSortingTypeIsNotNull() {
            addCriterion("sorting_type is not null");
            return (Criteria) this;
        }

        public Criteria andSortingTypeEqualTo(Byte value) {
            addCriterion("sorting_type =", value, "sortingType");
            return (Criteria) this;
        }

        public Criteria andSortingTypeNotEqualTo(Byte value) {
            addCriterion("sorting_type <>", value, "sortingType");
            return (Criteria) this;
        }

        public Criteria andSortingTypeGreaterThan(Byte value) {
            addCriterion("sorting_type >", value, "sortingType");
            return (Criteria) this;
        }

        public Criteria andSortingTypeGreaterThanOrEqualTo(Byte value) {
            addCriterion("sorting_type >=", value, "sortingType");
            return (Criteria) this;
        }

        public Criteria andSortingTypeLessThan(Byte value) {
            addCriterion("sorting_type <", value, "sortingType");
            return (Criteria) this;
        }

        public Criteria andSortingTypeLessThanOrEqualTo(Byte value) {
            addCriterion("sorting_type <=", value, "sortingType");
            return (Criteria) this;
        }

        public Criteria andSortingTypeIn(List<Byte> values) {
            addCriterion("sorting_type in", values, "sortingType");
            return (Criteria) this;
        }

        public Criteria andSortingTypeNotIn(List<Byte> values) {
            addCriterion("sorting_type not in", values, "sortingType");
            return (Criteria) this;
        }

        public Criteria andSortingTypeBetween(Byte value1, Byte value2) {
            addCriterion("sorting_type between", value1, value2, "sortingType");
            return (Criteria) this;
        }

        public Criteria andSortingTypeNotBetween(Byte value1, Byte value2) {
            addCriterion("sorting_type not between", value1, value2, "sortingType");
            return (Criteria) this;
        }

        public Criteria andBrandIdIsNull() {
            addCriterion("brand_id is null");
            return (Criteria) this;
        }

        public Criteria andBrandIdIsNotNull() {
            addCriterion("brand_id is not null");
            return (Criteria) this;
        }

        public Criteria andBrandIdEqualTo(Long value) {
            addCriterion("brand_id =", value, "brandId");
            return (Criteria) this;
        }

        public Criteria andBrandIdNotEqualTo(Long value) {
            addCriterion("brand_id <>", value, "brandId");
            return (Criteria) this;
        }

        public Criteria andBrandIdGreaterThan(Long value) {
            addCriterion("brand_id >", value, "brandId");
            return (Criteria) this;
        }

        public Criteria andBrandIdGreaterThanOrEqualTo(Long value) {
            addCriterion("brand_id >=", value, "brandId");
            return (Criteria) this;
        }

        public Criteria andBrandIdLessThan(Long value) {
            addCriterion("brand_id <", value, "brandId");
            return (Criteria) this;
        }

        public Criteria andBrandIdLessThanOrEqualTo(Long value) {
            addCriterion("brand_id <=", value, "brandId");
            return (Criteria) this;
        }

        public Criteria andBrandIdIn(List<Long> values) {
            addCriterion("brand_id in", values, "brandId");
            return (Criteria) this;
        }

        public Criteria andBrandIdNotIn(List<Long> values) {
            addCriterion("brand_id not in", values, "brandId");
            return (Criteria) this;
        }

        public Criteria andBrandIdBetween(Long value1, Long value2) {
            addCriterion("brand_id between", value1, value2, "brandId");
            return (Criteria) this;
        }

        public Criteria andBrandIdNotBetween(Long value1, Long value2) {
            addCriterion("brand_id not between", value1, value2, "brandId");
            return (Criteria) this;
        }

        public Criteria andBrandNameIsNull() {
            addCriterion("brand_name is null");
            return (Criteria) this;
        }

        public Criteria andBrandNameIsNotNull() {
            addCriterion("brand_name is not null");
            return (Criteria) this;
        }

        public Criteria andBrandNameEqualTo(String value) {
            addCriterion("brand_name =", value, "brandName");
            return (Criteria) this;
        }

        public Criteria andBrandNameNotEqualTo(String value) {
            addCriterion("brand_name <>", value, "brandName");
            return (Criteria) this;
        }

        public Criteria andBrandNameGreaterThan(String value) {
            addCriterion("brand_name >", value, "brandName");
            return (Criteria) this;
        }

        public Criteria andBrandNameGreaterThanOrEqualTo(String value) {
            addCriterion("brand_name >=", value, "brandName");
            return (Criteria) this;
        }

        public Criteria andBrandNameLessThan(String value) {
            addCriterion("brand_name <", value, "brandName");
            return (Criteria) this;
        }

        public Criteria andBrandNameLessThanOrEqualTo(String value) {
            addCriterion("brand_name <=", value, "brandName");
            return (Criteria) this;
        }

        public Criteria andBrandNameLike(String value) {
            addCriterion("brand_name like", value, "brandName");
            return (Criteria) this;
        }

        public Criteria andBrandNameNotLike(String value) {
            addCriterion("brand_name not like", value, "brandName");
            return (Criteria) this;
        }

        public Criteria andBrandNameIn(List<String> values) {
            addCriterion("brand_name in", values, "brandName");
            return (Criteria) this;
        }

        public Criteria andBrandNameNotIn(List<String> values) {
            addCriterion("brand_name not in", values, "brandName");
            return (Criteria) this;
        }

        public Criteria andBrandNameBetween(String value1, String value2) {
            addCriterion("brand_name between", value1, value2, "brandName");
            return (Criteria) this;
        }

        public Criteria andBrandNameNotBetween(String value1, String value2) {
            addCriterion("brand_name not between", value1, value2, "brandName");
            return (Criteria) this;
        }

        public Criteria andDesignerIdIsNull() {
            addCriterion("designer_id is null");
            return (Criteria) this;
        }

        public Criteria andDesignerIdIsNotNull() {
            addCriterion("designer_id is not null");
            return (Criteria) this;
        }

        public Criteria andDesignerIdEqualTo(String value) {
            addCriterion("designer_id =", value, "designerId");
            return (Criteria) this;
        }

        public Criteria andDesignerIdNotEqualTo(String value) {
            addCriterion("designer_id <>", value, "designerId");
            return (Criteria) this;
        }

        public Criteria andDesignerIdGreaterThan(String value) {
            addCriterion("designer_id >", value, "designerId");
            return (Criteria) this;
        }

        public Criteria andDesignerIdGreaterThanOrEqualTo(String value) {
            addCriterion("designer_id >=", value, "designerId");
            return (Criteria) this;
        }

        public Criteria andDesignerIdLessThan(String value) {
            addCriterion("designer_id <", value, "designerId");
            return (Criteria) this;
        }

        public Criteria andDesignerIdLessThanOrEqualTo(String value) {
            addCriterion("designer_id <=", value, "designerId");
            return (Criteria) this;
        }

        public Criteria andDesignerIdLike(String value) {
            addCriterion("designer_id like", value, "designerId");
            return (Criteria) this;
        }

        public Criteria andDesignerIdNotLike(String value) {
            addCriterion("designer_id not like", value, "designerId");
            return (Criteria) this;
        }

        public Criteria andDesignerIdIn(List<String> values) {
            addCriterion("designer_id in", values, "designerId");
            return (Criteria) this;
        }

        public Criteria andDesignerIdNotIn(List<String> values) {
            addCriterion("designer_id not in", values, "designerId");
            return (Criteria) this;
        }

        public Criteria andDesignerIdBetween(String value1, String value2) {
            addCriterion("designer_id between", value1, value2, "designerId");
            return (Criteria) this;
        }

        public Criteria andDesignerIdNotBetween(String value1, String value2) {
            addCriterion("designer_id not between", value1, value2, "designerId");
            return (Criteria) this;
        }

        public Criteria andColorCodeIsNull() {
            addCriterion("color_code is null");
            return (Criteria) this;
        }

        public Criteria andColorCodeIsNotNull() {
            addCriterion("color_code is not null");
            return (Criteria) this;
        }

        public Criteria andColorCodeEqualTo(String value) {
            addCriterion("color_code =", value, "colorCode");
            return (Criteria) this;
        }

        public Criteria andColorCodeNotEqualTo(String value) {
            addCriterion("color_code <>", value, "colorCode");
            return (Criteria) this;
        }

        public Criteria andColorCodeGreaterThan(String value) {
            addCriterion("color_code >", value, "colorCode");
            return (Criteria) this;
        }

        public Criteria andColorCodeGreaterThanOrEqualTo(String value) {
            addCriterion("color_code >=", value, "colorCode");
            return (Criteria) this;
        }

        public Criteria andColorCodeLessThan(String value) {
            addCriterion("color_code <", value, "colorCode");
            return (Criteria) this;
        }

        public Criteria andColorCodeLessThanOrEqualTo(String value) {
            addCriterion("color_code <=", value, "colorCode");
            return (Criteria) this;
        }

        public Criteria andColorCodeLike(String value) {
            addCriterion("color_code like", value, "colorCode");
            return (Criteria) this;
        }

        public Criteria andColorCodeNotLike(String value) {
            addCriterion("color_code not like", value, "colorCode");
            return (Criteria) this;
        }

        public Criteria andColorCodeIn(List<String> values) {
            addCriterion("color_code in", values, "colorCode");
            return (Criteria) this;
        }

        public Criteria andColorCodeNotIn(List<String> values) {
            addCriterion("color_code not in", values, "colorCode");
            return (Criteria) this;
        }

        public Criteria andColorCodeBetween(String value1, String value2) {
            addCriterion("color_code between", value1, value2, "colorCode");
            return (Criteria) this;
        }

        public Criteria andColorCodeNotBetween(String value1, String value2) {
            addCriterion("color_code not between", value1, value2, "colorCode");
            return (Criteria) this;
        }

        public Criteria andCategoryIdIsNull() {
            addCriterion("category_id is null");
            return (Criteria) this;
        }

        public Criteria andCategoryIdIsNotNull() {
            addCriterion("category_id is not null");
            return (Criteria) this;
        }

        public Criteria andCategoryIdEqualTo(Long value) {
            addCriterion("category_id =", value, "categoryId");
            return (Criteria) this;
        }

        public Criteria andCategoryIdNotEqualTo(Long value) {
            addCriterion("category_id <>", value, "categoryId");
            return (Criteria) this;
        }

        public Criteria andCategoryIdGreaterThan(Long value) {
            addCriterion("category_id >", value, "categoryId");
            return (Criteria) this;
        }

        public Criteria andCategoryIdGreaterThanOrEqualTo(Long value) {
            addCriterion("category_id >=", value, "categoryId");
            return (Criteria) this;
        }

        public Criteria andCategoryIdLessThan(Long value) {
            addCriterion("category_id <", value, "categoryId");
            return (Criteria) this;
        }

        public Criteria andCategoryIdLessThanOrEqualTo(Long value) {
            addCriterion("category_id <=", value, "categoryId");
            return (Criteria) this;
        }

        public Criteria andCategoryIdIn(List<Long> values) {
            addCriterion("category_id in", values, "categoryId");
            return (Criteria) this;
        }

        public Criteria andCategoryIdNotIn(List<Long> values) {
            addCriterion("category_id not in", values, "categoryId");
            return (Criteria) this;
        }

        public Criteria andCategoryIdBetween(Long value1, Long value2) {
            addCriterion("category_id between", value1, value2, "categoryId");
            return (Criteria) this;
        }

        public Criteria andCategoryIdNotBetween(Long value1, Long value2) {
            addCriterion("category_id not between", value1, value2, "categoryId");
            return (Criteria) this;
        }

        public Criteria andSizeIsNull() {
            addCriterion("size is null");
            return (Criteria) this;
        }

        public Criteria andSizeIsNotNull() {
            addCriterion("size is not null");
            return (Criteria) this;
        }

        public Criteria andSizeEqualTo(String value) {
            addCriterion("size =", value, "size");
            return (Criteria) this;
        }

        public Criteria andSizeNotEqualTo(String value) {
            addCriterion("size <>", value, "size");
            return (Criteria) this;
        }

        public Criteria andSizeGreaterThan(String value) {
            addCriterion("size >", value, "size");
            return (Criteria) this;
        }

        public Criteria andSizeGreaterThanOrEqualTo(String value) {
            addCriterion("size >=", value, "size");
            return (Criteria) this;
        }

        public Criteria andSizeLessThan(String value) {
            addCriterion("size <", value, "size");
            return (Criteria) this;
        }

        public Criteria andSizeLessThanOrEqualTo(String value) {
            addCriterion("size <=", value, "size");
            return (Criteria) this;
        }

        public Criteria andSizeLike(String value) {
            addCriterion("size like", value, "size");
            return (Criteria) this;
        }

        public Criteria andSizeNotLike(String value) {
            addCriterion("size not like", value, "size");
            return (Criteria) this;
        }

        public Criteria andSizeIn(List<String> values) {
            addCriterion("size in", values, "size");
            return (Criteria) this;
        }

        public Criteria andSizeNotIn(List<String> values) {
            addCriterion("size not in", values, "size");
            return (Criteria) this;
        }

        public Criteria andSizeBetween(String value1, String value2) {
            addCriterion("size between", value1, value2, "size");
            return (Criteria) this;
        }

        public Criteria andSizeNotBetween(String value1, String value2) {
            addCriterion("size not between", value1, value2, "size");
            return (Criteria) this;
        }

        public Criteria andStockStatusIsNull() {
            addCriterion("stock_status is null");
            return (Criteria) this;
        }

        public Criteria andStockStatusIsNotNull() {
            addCriterion("stock_status is not null");
            return (Criteria) this;
        }

        public Criteria andStockStatusEqualTo(Byte value) {
            addCriterion("stock_status =", value, "stockStatus");
            return (Criteria) this;
        }

        public Criteria andStockStatusNotEqualTo(Byte value) {
            addCriterion("stock_status <>", value, "stockStatus");
            return (Criteria) this;
        }

        public Criteria andStockStatusGreaterThan(Byte value) {
            addCriterion("stock_status >", value, "stockStatus");
            return (Criteria) this;
        }

        public Criteria andStockStatusGreaterThanOrEqualTo(Byte value) {
            addCriterion("stock_status >=", value, "stockStatus");
            return (Criteria) this;
        }

        public Criteria andStockStatusLessThan(Byte value) {
            addCriterion("stock_status <", value, "stockStatus");
            return (Criteria) this;
        }

        public Criteria andStockStatusLessThanOrEqualTo(Byte value) {
            addCriterion("stock_status <=", value, "stockStatus");
            return (Criteria) this;
        }

        public Criteria andStockStatusIn(List<Byte> values) {
            addCriterion("stock_status in", values, "stockStatus");
            return (Criteria) this;
        }

        public Criteria andStockStatusNotIn(List<Byte> values) {
            addCriterion("stock_status not in", values, "stockStatus");
            return (Criteria) this;
        }

        public Criteria andStockStatusBetween(Byte value1, Byte value2) {
            addCriterion("stock_status between", value1, value2, "stockStatus");
            return (Criteria) this;
        }

        public Criteria andStockStatusNotBetween(Byte value1, Byte value2) {
            addCriterion("stock_status not between", value1, value2, "stockStatus");
            return (Criteria) this;
        }

        public Criteria andThirdShipmentIdIsNull() {
            addCriterion("third_shipment_id is null");
            return (Criteria) this;
        }

        public Criteria andThirdShipmentIdIsNotNull() {
            addCriterion("third_shipment_id is not null");
            return (Criteria) this;
        }

        public Criteria andThirdShipmentIdEqualTo(Long value) {
            addCriterion("third_shipment_id =", value, "thirdShipmentId");
            return (Criteria) this;
        }

        public Criteria andThirdShipmentIdNotEqualTo(Long value) {
            addCriterion("third_shipment_id <>", value, "thirdShipmentId");
            return (Criteria) this;
        }

        public Criteria andThirdShipmentIdGreaterThan(Long value) {
            addCriterion("third_shipment_id >", value, "thirdShipmentId");
            return (Criteria) this;
        }

        public Criteria andThirdShipmentIdGreaterThanOrEqualTo(Long value) {
            addCriterion("third_shipment_id >=", value, "thirdShipmentId");
            return (Criteria) this;
        }

        public Criteria andThirdShipmentIdLessThan(Long value) {
            addCriterion("third_shipment_id <", value, "thirdShipmentId");
            return (Criteria) this;
        }

        public Criteria andThirdShipmentIdLessThanOrEqualTo(Long value) {
            addCriterion("third_shipment_id <=", value, "thirdShipmentId");
            return (Criteria) this;
        }

        public Criteria andThirdShipmentIdIn(List<Long> values) {
            addCriterion("third_shipment_id in", values, "thirdShipmentId");
            return (Criteria) this;
        }

        public Criteria andThirdShipmentIdNotIn(List<Long> values) {
            addCriterion("third_shipment_id not in", values, "thirdShipmentId");
            return (Criteria) this;
        }

        public Criteria andThirdShipmentIdBetween(Long value1, Long value2) {
            addCriterion("third_shipment_id between", value1, value2, "thirdShipmentId");
            return (Criteria) this;
        }

        public Criteria andThirdShipmentIdNotBetween(Long value1, Long value2) {
            addCriterion("third_shipment_id not between", value1, value2, "thirdShipmentId");
            return (Criteria) this;
        }

        public Criteria andCreateTimeIsNull() {
            addCriterion("create_time is null");
            return (Criteria) this;
        }

        public Criteria andCreateTimeIsNotNull() {
            addCriterion("create_time is not null");
            return (Criteria) this;
        }

        public Criteria andCreateTimeEqualTo(Date value) {
            addCriterion("create_time =", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeNotEqualTo(Date value) {
            addCriterion("create_time <>", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeGreaterThan(Date value) {
            addCriterion("create_time >", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeGreaterThanOrEqualTo(Date value) {
            addCriterion("create_time >=", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeLessThan(Date value) {
            addCriterion("create_time <", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeLessThanOrEqualTo(Date value) {
            addCriterion("create_time <=", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeIn(List<Date> values) {
            addCriterion("create_time in", values, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeNotIn(List<Date> values) {
            addCriterion("create_time not in", values, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeBetween(Date value1, Date value2) {
            addCriterion("create_time between", value1, value2, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeNotBetween(Date value1, Date value2) {
            addCriterion("create_time not between", value1, value2, "createTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeIsNull() {
            addCriterion("update_time is null");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeIsNotNull() {
            addCriterion("update_time is not null");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeEqualTo(Date value) {
            addCriterion("update_time =", value, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeNotEqualTo(Date value) {
            addCriterion("update_time <>", value, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeGreaterThan(Date value) {
            addCriterion("update_time >", value, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeGreaterThanOrEqualTo(Date value) {
            addCriterion("update_time >=", value, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeLessThan(Date value) {
            addCriterion("update_time <", value, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeLessThanOrEqualTo(Date value) {
            addCriterion("update_time <=", value, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeIn(List<Date> values) {
            addCriterion("update_time in", values, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeNotIn(List<Date> values) {
            addCriterion("update_time not in", values, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeBetween(Date value1, Date value2) {
            addCriterion("update_time between", value1, value2, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeNotBetween(Date value1, Date value2) {
            addCriterion("update_time not between", value1, value2, "updateTime");
            return (Criteria) this;
        }

        public Criteria andIsDeletedIsNull() {
            addCriterion("is_deleted is null");
            return (Criteria) this;
        }

        public Criteria andIsDeletedIsNotNull() {
            addCriterion("is_deleted is not null");
            return (Criteria) this;
        }

        public Criteria andIsDeletedEqualTo(Integer value) {
            addCriterion("is_deleted =", value, "isDeleted");
            return (Criteria) this;
        }

        public Criteria andIsDeletedNotEqualTo(Integer value) {
            addCriterion("is_deleted <>", value, "isDeleted");
            return (Criteria) this;
        }

        public Criteria andIsDeletedGreaterThan(Integer value) {
            addCriterion("is_deleted >", value, "isDeleted");
            return (Criteria) this;
        }

        public Criteria andIsDeletedGreaterThanOrEqualTo(Integer value) {
            addCriterion("is_deleted >=", value, "isDeleted");
            return (Criteria) this;
        }

        public Criteria andIsDeletedLessThan(Integer value) {
            addCriterion("is_deleted <", value, "isDeleted");
            return (Criteria) this;
        }

        public Criteria andIsDeletedLessThanOrEqualTo(Integer value) {
            addCriterion("is_deleted <=", value, "isDeleted");
            return (Criteria) this;
        }

        public Criteria andIsDeletedIn(List<Integer> values) {
            addCriterion("is_deleted in", values, "isDeleted");
            return (Criteria) this;
        }

        public Criteria andIsDeletedNotIn(List<Integer> values) {
            addCriterion("is_deleted not in", values, "isDeleted");
            return (Criteria) this;
        }

        public Criteria andIsDeletedBetween(Integer value1, Integer value2) {
            addCriterion("is_deleted between", value1, value2, "isDeleted");
            return (Criteria) this;
        }

        public Criteria andIsDeletedNotBetween(Integer value1, Integer value2) {
            addCriterion("is_deleted not between", value1, value2, "isDeleted");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table third_warehouse
     *
     * @mbg.generated do_not_delete_during_merge
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table third_warehouse
     *
     * @mbg.generated
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}