package com.intramirror.order.api.model;

import java.util.Date;

public class ThirdWarehouse {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column third_warehouse.id
     *
     * @mbg.generated
     */
    private Long id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column third_warehouse.oversea_shipment_no
     *
     * @mbg.generated
     */
    private String overseaShipmentNo;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column third_warehouse.oversea_shipment_ship_time
     *
     * @mbg.generated
     */
    private Date overseaShipmentShipTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column third_warehouse.awb_no
     *
     * @mbg.generated
     */
    private String awbNo;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column third_warehouse.order_line_num
     *
     * @mbg.generated
     */
    private String orderLineNum;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column third_warehouse.order_image
     *
     * @mbg.generated
     */
    private String orderImage;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column third_warehouse.sorting_type
     *
     * @mbg.generated
     */
    private Byte sortingType;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column third_warehouse.brand_id
     *
     * @mbg.generated
     */
    private Long brandId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column third_warehouse.brand_name
     *
     * @mbg.generated
     */
    private String brandName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column third_warehouse.designer_id
     *
     * @mbg.generated
     */
    private String designerId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column third_warehouse.color_code
     *
     * @mbg.generated
     */
    private String colorCode;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column third_warehouse.category_id
     *
     * @mbg.generated
     */
    private Long categoryId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column third_warehouse.size
     *
     * @mbg.generated
     */
    private String size;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column third_warehouse.stock_status
     *
     * @mbg.generated
     */
    private Byte stockStatus;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column third_warehouse.third_shipment_id
     *
     * @mbg.generated
     */
    private Long thirdShipmentId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column third_warehouse.create_time
     *
     * @mbg.generated
     */
    private Date createTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column third_warehouse.update_time
     *
     * @mbg.generated
     */
    private Date updateTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column third_warehouse.is_deleted
     *
     * @mbg.generated
     */
    private Integer isDeleted;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column third_warehouse.id
     *
     * @return the value of third_warehouse.id
     *
     * @mbg.generated
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column third_warehouse.id
     *
     * @param id the value for third_warehouse.id
     *
     * @mbg.generated
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column third_warehouse.oversea_shipment_no
     *
     * @return the value of third_warehouse.oversea_shipment_no
     *
     * @mbg.generated
     */
    public String getOverseaShipmentNo() {
        return overseaShipmentNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column third_warehouse.oversea_shipment_no
     *
     * @param overseaShipmentNo the value for third_warehouse.oversea_shipment_no
     *
     * @mbg.generated
     */
    public void setOverseaShipmentNo(String overseaShipmentNo) {
        this.overseaShipmentNo = overseaShipmentNo == null ? null : overseaShipmentNo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column third_warehouse.oversea_shipment_ship_time
     *
     * @return the value of third_warehouse.oversea_shipment_ship_time
     *
     * @mbg.generated
     */
    public Date getOverseaShipmentShipTime() {
        return overseaShipmentShipTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column third_warehouse.oversea_shipment_ship_time
     *
     * @param overseaShipmentShipTime the value for third_warehouse.oversea_shipment_ship_time
     *
     * @mbg.generated
     */
    public void setOverseaShipmentShipTime(Date overseaShipmentShipTime) {
        this.overseaShipmentShipTime = overseaShipmentShipTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column third_warehouse.awb_no
     *
     * @return the value of third_warehouse.awb_no
     *
     * @mbg.generated
     */
    public String getAwbNo() {
        return awbNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column third_warehouse.awb_no
     *
     * @param awbNo the value for third_warehouse.awb_no
     *
     * @mbg.generated
     */
    public void setAwbNo(String awbNo) {
        this.awbNo = awbNo == null ? null : awbNo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column third_warehouse.order_line_num
     *
     * @return the value of third_warehouse.order_line_num
     *
     * @mbg.generated
     */
    public String getOrderLineNum() {
        return orderLineNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column third_warehouse.order_line_num
     *
     * @param orderLineNum the value for third_warehouse.order_line_num
     *
     * @mbg.generated
     */
    public void setOrderLineNum(String orderLineNum) {
        this.orderLineNum = orderLineNum == null ? null : orderLineNum.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column third_warehouse.order_image
     *
     * @return the value of third_warehouse.order_image
     *
     * @mbg.generated
     */
    public String getOrderImage() {
        return orderImage;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column third_warehouse.order_image
     *
     * @param orderImage the value for third_warehouse.order_image
     *
     * @mbg.generated
     */
    public void setOrderImage(String orderImage) {
        this.orderImage = orderImage == null ? null : orderImage.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column third_warehouse.sorting_type
     *
     * @return the value of third_warehouse.sorting_type
     *
     * @mbg.generated
     */
    public Byte getSortingType() {
        return sortingType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column third_warehouse.sorting_type
     *
     * @param sortingType the value for third_warehouse.sorting_type
     *
     * @mbg.generated
     */
    public void setSortingType(Byte sortingType) {
        this.sortingType = sortingType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column third_warehouse.brand_id
     *
     * @return the value of third_warehouse.brand_id
     *
     * @mbg.generated
     */
    public Long getBrandId() {
        return brandId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column third_warehouse.brand_id
     *
     * @param brandId the value for third_warehouse.brand_id
     *
     * @mbg.generated
     */
    public void setBrandId(Long brandId) {
        this.brandId = brandId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column third_warehouse.brand_name
     *
     * @return the value of third_warehouse.brand_name
     *
     * @mbg.generated
     */
    public String getBrandName() {
        return brandName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column third_warehouse.brand_name
     *
     * @param brandName the value for third_warehouse.brand_name
     *
     * @mbg.generated
     */
    public void setBrandName(String brandName) {
        this.brandName = brandName == null ? null : brandName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column third_warehouse.designer_id
     *
     * @return the value of third_warehouse.designer_id
     *
     * @mbg.generated
     */
    public String getDesignerId() {
        return designerId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column third_warehouse.designer_id
     *
     * @param designerId the value for third_warehouse.designer_id
     *
     * @mbg.generated
     */
    public void setDesignerId(String designerId) {
        this.designerId = designerId == null ? null : designerId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column third_warehouse.color_code
     *
     * @return the value of third_warehouse.color_code
     *
     * @mbg.generated
     */
    public String getColorCode() {
        return colorCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column third_warehouse.color_code
     *
     * @param colorCode the value for third_warehouse.color_code
     *
     * @mbg.generated
     */
    public void setColorCode(String colorCode) {
        this.colorCode = colorCode == null ? null : colorCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column third_warehouse.category_id
     *
     * @return the value of third_warehouse.category_id
     *
     * @mbg.generated
     */
    public Long getCategoryId() {
        return categoryId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column third_warehouse.category_id
     *
     * @param categoryId the value for third_warehouse.category_id
     *
     * @mbg.generated
     */
    public void setCategoryId(Long categoryId) {
        this.categoryId = categoryId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column third_warehouse.size
     *
     * @return the value of third_warehouse.size
     *
     * @mbg.generated
     */
    public String getSize() {
        return size;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column third_warehouse.size
     *
     * @param size the value for third_warehouse.size
     *
     * @mbg.generated
     */
    public void setSize(String size) {
        this.size = size == null ? null : size.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column third_warehouse.stock_status
     *
     * @return the value of third_warehouse.stock_status
     *
     * @mbg.generated
     */
    public Byte getStockStatus() {
        return stockStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column third_warehouse.stock_status
     *
     * @param stockStatus the value for third_warehouse.stock_status
     *
     * @mbg.generated
     */
    public void setStockStatus(Byte stockStatus) {
        this.stockStatus = stockStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column third_warehouse.third_shipment_id
     *
     * @return the value of third_warehouse.third_shipment_id
     *
     * @mbg.generated
     */
    public Long getThirdShipmentId() {
        return thirdShipmentId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column third_warehouse.third_shipment_id
     *
     * @param thirdShipmentId the value for third_warehouse.third_shipment_id
     *
     * @mbg.generated
     */
    public void setThirdShipmentId(Long thirdShipmentId) {
        this.thirdShipmentId = thirdShipmentId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column third_warehouse.create_time
     *
     * @return the value of third_warehouse.create_time
     *
     * @mbg.generated
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column third_warehouse.create_time
     *
     * @param createTime the value for third_warehouse.create_time
     *
     * @mbg.generated
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column third_warehouse.update_time
     *
     * @return the value of third_warehouse.update_time
     *
     * @mbg.generated
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column third_warehouse.update_time
     *
     * @param updateTime the value for third_warehouse.update_time
     *
     * @mbg.generated
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column third_warehouse.is_deleted
     *
     * @return the value of third_warehouse.is_deleted
     *
     * @mbg.generated
     */
    public Integer getIsDeleted() {
        return isDeleted;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column third_warehouse.is_deleted
     *
     * @param isDeleted the value for third_warehouse.is_deleted
     *
     * @mbg.generated
     */
    public void setIsDeleted(Integer isDeleted) {
        this.isDeleted = isDeleted;
    }
}