package com.intramirror.main.core.mapper;

import com.intramirror.main.api.model.AddressDistrict;

import java.util.List;
import java.util.Map;

public interface AddressDistrictMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table address_district
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Long addressDistrictId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table address_district
     *
     * @mbggenerated
     */
    int insert(AddressDistrict record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table address_district
     *
     * @mbggenerated
     */
    int insertSelective(AddressDistrict record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table address_district
     *
     * @mbggenerated
     */
    AddressDistrict selectByPrimaryKey(Long addressDistrictId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table address_district
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(AddressDistrict record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table address_district
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(AddressDistrict record);

    List<Map<String, Object>> getAddressDistrictByCityId(Long cityId);
}