package com.intramirror.main.core.mapper;

import com.intramirror.main.api.model.AddressCountry;

public interface AddressCountryMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table address_country
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Long addressCountryId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table address_country
     *
     * @mbggenerated
     */
    int insert(AddressCountry record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table address_country
     *
     * @mbggenerated
     */
    int insertSelective(AddressCountry record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table address_country
     *
     * @mbggenerated
     */
    AddressCountry selectByPrimaryKey(Long addressCountryId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table address_country
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(AddressCountry record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table address_country
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(AddressCountry record);

    AddressCountry getAddressCountryByName(String name);
}