package com.intramirror.main.core.mapper;

import java.util.List;
import java.util.Map;

import com.intramirror.main.api.model.ApiEndPoint;

public interface ApiEndPointMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table api_end_point
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Long apiEndPointId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table api_end_point
     *
     * @mbggenerated
     */
    int insert(ApiEndPoint record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table api_end_point
     *
     * @mbggenerated
     */
    int insertSelective(ApiEndPoint record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table api_end_point
     *
     * @mbggenerated
     */
    ApiEndPoint selectByPrimaryKey(Long apiEndPointId);
    
    
    
	/**
	 * 根据系统跟接口名称   获取相关信息
	 * @param system name
	 * @return
	 */
	List<Map<String,Object>> getapiEndpointInfoByCondition(Map<String,Object> param);
    
	

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table api_end_point
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(ApiEndPoint record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table api_end_point
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(ApiEndPoint record);
}