package com.intramirror.main.core.mapper;

import java.util.List;
import java.util.Map;

import com.intramirror.main.api.model.ApiParameter;

public interface ApiParameterMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table api_parameter
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Long apiParameterId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table api_parameter
     *
     * @mbggenerated
     */
    int insert(ApiParameter record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table api_parameter
     *
     * @mbggenerated
     */
    int insertSelective(ApiParameter record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table api_parameter
     *
     * @mbggenerated
     */
    ApiParameter selectByPrimaryKey(Long apiParameterId);
    
    
	/**
	 * 根据api_end_point_id 获取相关信息
	 * @param api_end_point_id
	 * @return
	 */
	List<Map<String,Object>> getapiParameterByCondition(Map<String,Object> param);
    

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table api_parameter
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(ApiParameter record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table api_parameter
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(ApiParameter record);
    
    /**
     * 根据key值修改
     * @param map
     * @return
     */
    int updateApiParameterByKey(Map<String, Object> map);
}