package com.intramirror.main.core.mapper;

import com.intramirror.main.api.model.Geography;

import java.util.List;
import java.util.Map;

public interface GeographyMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table geography
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Long geographyId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table geography
     *
     * @mbggenerated
     */
    int insert(Geography record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table geography
     *
     * @mbggenerated
     */
    int insertSelective(Geography record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table geography
     *
     * @mbggenerated
     */
    Geography selectByPrimaryKey(Long geographyId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table geography
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(Geography record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table geography
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(Geography record);

    List<Map<String, Object>> getGeographyList();
}