package com.intramirror.main.core.mapper;

import com.intramirror.main.api.model.Tax;
import org.apache.ibatis.annotations.Param;

import java.util.List;
import java.util.Map;

public interface TaxMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tax
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer taxId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tax
     *
     * @mbggenerated
     */
    int insert(Tax record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tax
     *
     * @mbggenerated
     */
    int insertSelective(Tax record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tax
     *
     * @mbggenerated
     */
    Tax selectByPrimaryKey(Integer taxId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tax
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(Tax record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tax
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(Tax record);

    List<Map<String, Object>> getTaxByCategoryId(@Param("taxType") String taxType,@Param("categoryIds") String[] categoryIds);

    List<Map<String, Object>> getTaxRateListById(@Param("fromCountryId") String fromCountryId,@Param("taxType") String taxType);

    List<Tax> getTaxByAddressCountryId(Long addressCountryId);
}