package com.intramirror.payment.api.model;

import java.util.Date;

public class PaymentResult {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column payment_result.payment_result_id
     *
     * @mbggenerated
     */
    private Long paymentResultId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column payment_result.payment_id
     *
     * @mbggenerated
     */
    private Long paymentId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column payment_result.marchant_id
     *
     * @mbggenerated
     */
    private String marchantId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column payment_result.request_id
     *
     * @mbggenerated
     */
    private String requestId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column payment_result.scan_code
     *
     * @mbggenerated
     */
    private String scanCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column payment_result.app_params
     *
     * @mbggenerated
     */
    private String appParams;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column payment_result.redirect_url
     *
     * @mbggenerated
     */
    private String redirectUrl;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column payment_result.serial_number
     *
     * @mbggenerated
     */
    private String serialNumber;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column payment_result.total_refund_count
     *
     * @mbggenerated
     */
    private String totalRefundCount;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column payment_result.total_refund_amount
     *
     * @mbggenerated
     */
    private String totalRefundAmount;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column payment_result.order_currency
     *
     * @mbggenerated
     */
    private String orderCurrency;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column payment_result.order_amount
     *
     * @mbggenerated
     */
    private String orderAmount;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column payment_result.process_status
     *
     * @mbggenerated
     */
    private String processStatus;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column payment_result.complete_date_time
     *
     * @mbggenerated
     */
    private Date completeDateTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column payment_result.remark
     *
     * @mbggenerated
     */
    private String remark;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column payment_result.hmac
     *
     * @mbggenerated
     */
    private String hmac;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column payment_result.created_at
     *
     * @mbggenerated
     */
    private Date createdAt;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column payment_result.update_at
     *
     * @mbggenerated
     */
    private Date updateAt;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column payment_result.bind_card_id
     *
     * @mbggenerated
     */
    private String bindCardId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column payment_result.payment_result_id
     *
     * @return the value of payment_result.payment_result_id
     *
     * @mbggenerated
     */
    public Long getPaymentResultId() {
        return paymentResultId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column payment_result.payment_result_id
     *
     * @param paymentResultId the value for payment_result.payment_result_id
     *
     * @mbggenerated
     */
    public void setPaymentResultId(Long paymentResultId) {
        this.paymentResultId = paymentResultId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column payment_result.payment_id
     *
     * @return the value of payment_result.payment_id
     *
     * @mbggenerated
     */
    public Long getPaymentId() {
        return paymentId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column payment_result.payment_id
     *
     * @param paymentId the value for payment_result.payment_id
     *
     * @mbggenerated
     */
    public void setPaymentId(Long paymentId) {
        this.paymentId = paymentId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column payment_result.marchant_id
     *
     * @return the value of payment_result.marchant_id
     *
     * @mbggenerated
     */
    public String getMarchantId() {
        return marchantId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column payment_result.marchant_id
     *
     * @param marchantId the value for payment_result.marchant_id
     *
     * @mbggenerated
     */
    public void setMarchantId(String marchantId) {
        this.marchantId = marchantId == null ? null : marchantId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column payment_result.request_id
     *
     * @return the value of payment_result.request_id
     *
     * @mbggenerated
     */
    public String getRequestId() {
        return requestId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column payment_result.request_id
     *
     * @param requestId the value for payment_result.request_id
     *
     * @mbggenerated
     */
    public void setRequestId(String requestId) {
        this.requestId = requestId == null ? null : requestId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column payment_result.scan_code
     *
     * @return the value of payment_result.scan_code
     *
     * @mbggenerated
     */
    public String getScanCode() {
        return scanCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column payment_result.scan_code
     *
     * @param scanCode the value for payment_result.scan_code
     *
     * @mbggenerated
     */
    public void setScanCode(String scanCode) {
        this.scanCode = scanCode == null ? null : scanCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column payment_result.app_params
     *
     * @return the value of payment_result.app_params
     *
     * @mbggenerated
     */
    public String getAppParams() {
        return appParams;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column payment_result.app_params
     *
     * @param appParams the value for payment_result.app_params
     *
     * @mbggenerated
     */
    public void setAppParams(String appParams) {
        this.appParams = appParams == null ? null : appParams.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column payment_result.redirect_url
     *
     * @return the value of payment_result.redirect_url
     *
     * @mbggenerated
     */
    public String getRedirectUrl() {
        return redirectUrl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column payment_result.redirect_url
     *
     * @param redirectUrl the value for payment_result.redirect_url
     *
     * @mbggenerated
     */
    public void setRedirectUrl(String redirectUrl) {
        this.redirectUrl = redirectUrl == null ? null : redirectUrl.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column payment_result.serial_number
     *
     * @return the value of payment_result.serial_number
     *
     * @mbggenerated
     */
    public String getSerialNumber() {
        return serialNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column payment_result.serial_number
     *
     * @param serialNumber the value for payment_result.serial_number
     *
     * @mbggenerated
     */
    public void setSerialNumber(String serialNumber) {
        this.serialNumber = serialNumber == null ? null : serialNumber.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column payment_result.total_refund_count
     *
     * @return the value of payment_result.total_refund_count
     *
     * @mbggenerated
     */
    public String getTotalRefundCount() {
        return totalRefundCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column payment_result.total_refund_count
     *
     * @param totalRefundCount the value for payment_result.total_refund_count
     *
     * @mbggenerated
     */
    public void setTotalRefundCount(String totalRefundCount) {
        this.totalRefundCount = totalRefundCount == null ? null : totalRefundCount.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column payment_result.total_refund_amount
     *
     * @return the value of payment_result.total_refund_amount
     *
     * @mbggenerated
     */
    public String getTotalRefundAmount() {
        return totalRefundAmount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column payment_result.total_refund_amount
     *
     * @param totalRefundAmount the value for payment_result.total_refund_amount
     *
     * @mbggenerated
     */
    public void setTotalRefundAmount(String totalRefundAmount) {
        this.totalRefundAmount = totalRefundAmount == null ? null : totalRefundAmount.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column payment_result.order_currency
     *
     * @return the value of payment_result.order_currency
     *
     * @mbggenerated
     */
    public String getOrderCurrency() {
        return orderCurrency;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column payment_result.order_currency
     *
     * @param orderCurrency the value for payment_result.order_currency
     *
     * @mbggenerated
     */
    public void setOrderCurrency(String orderCurrency) {
        this.orderCurrency = orderCurrency == null ? null : orderCurrency.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column payment_result.order_amount
     *
     * @return the value of payment_result.order_amount
     *
     * @mbggenerated
     */
    public String getOrderAmount() {
        return orderAmount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column payment_result.order_amount
     *
     * @param orderAmount the value for payment_result.order_amount
     *
     * @mbggenerated
     */
    public void setOrderAmount(String orderAmount) {
        this.orderAmount = orderAmount == null ? null : orderAmount.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column payment_result.process_status
     *
     * @return the value of payment_result.process_status
     *
     * @mbggenerated
     */
    public String getProcessStatus() {
        return processStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column payment_result.process_status
     *
     * @param processStatus the value for payment_result.process_status
     *
     * @mbggenerated
     */
    public void setProcessStatus(String processStatus) {
        this.processStatus = processStatus == null ? null : processStatus.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column payment_result.complete_date_time
     *
     * @return the value of payment_result.complete_date_time
     *
     * @mbggenerated
     */
    public Date getCompleteDateTime() {
        return completeDateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column payment_result.complete_date_time
     *
     * @param completeDateTime the value for payment_result.complete_date_time
     *
     * @mbggenerated
     */
    public void setCompleteDateTime(Date completeDateTime) {
        this.completeDateTime = completeDateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column payment_result.remark
     *
     * @return the value of payment_result.remark
     *
     * @mbggenerated
     */
    public String getRemark() {
        return remark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column payment_result.remark
     *
     * @param remark the value for payment_result.remark
     *
     * @mbggenerated
     */
    public void setRemark(String remark) {
        this.remark = remark == null ? null : remark.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column payment_result.hmac
     *
     * @return the value of payment_result.hmac
     *
     * @mbggenerated
     */
    public String getHmac() {
        return hmac;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column payment_result.hmac
     *
     * @param hmac the value for payment_result.hmac
     *
     * @mbggenerated
     */
    public void setHmac(String hmac) {
        this.hmac = hmac == null ? null : hmac.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column payment_result.created_at
     *
     * @return the value of payment_result.created_at
     *
     * @mbggenerated
     */
    public Date getCreatedAt() {
        return createdAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column payment_result.created_at
     *
     * @param createdAt the value for payment_result.created_at
     *
     * @mbggenerated
     */
    public void setCreatedAt(Date createdAt) {
        this.createdAt = createdAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column payment_result.update_at
     *
     * @return the value of payment_result.update_at
     *
     * @mbggenerated
     */
    public Date getUpdateAt() {
        return updateAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column payment_result.update_at
     *
     * @param updateAt the value for payment_result.update_at
     *
     * @mbggenerated
     */
    public void setUpdateAt(Date updateAt) {
        this.updateAt = updateAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column payment_result.bind_card_id
     *
     * @return the value of payment_result.bind_card_id
     *
     * @mbggenerated
     */
    public String getBindCardId() {
        return bindCardId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column payment_result.bind_card_id
     *
     * @param bindCardId the value for payment_result.bind_card_id
     *
     * @mbggenerated
     */
    public void setBindCardId(String bindCardId) {
        this.bindCardId = bindCardId == null ? null : bindCardId.trim();
    }
}