package com.intramirror.logistics.api.model;

import java.math.BigDecimal;

public class Tax {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tax.tax_id
     *
     * @mbggenerated
     */
    private Integer taxId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tax.tax_type
     *
     * @mbggenerated
     */
    private Integer taxType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tax.tax_rate
     *
     * @mbggenerated
     */
    private BigDecimal taxRate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tax.markup_rate
     *
     * @mbggenerated
     */
    private BigDecimal markupRate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tax.tax_number
     *
     * @mbggenerated
     */
    private String taxNumber;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tax.tax_product_category
     *
     * @mbggenerated
     */
    private String taxProductCategory;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tax.tax_reference_amt
     *
     * @mbggenerated
     */
    private BigDecimal taxReferenceAmt;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tax.tax_reference_currency
     *
     * @mbggenerated
     */
    private String taxReferenceCurrency;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tax.category_id
     *
     * @mbggenerated
     */
    private Long categoryId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tax.address_country_id
     *
     * @mbggenerated
     */
    private Long addressCountryId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tax.tax_id
     *
     * @return the value of tax.tax_id
     *
     * @mbggenerated
     */
    public Integer getTaxId() {
        return taxId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tax.tax_id
     *
     * @param taxId the value for tax.tax_id
     *
     * @mbggenerated
     */
    public void setTaxId(Integer taxId) {
        this.taxId = taxId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tax.tax_type
     *
     * @return the value of tax.tax_type
     *
     * @mbggenerated
     */
    public Integer getTaxType() {
        return taxType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tax.tax_type
     *
     * @param taxType the value for tax.tax_type
     *
     * @mbggenerated
     */
    public void setTaxType(Integer taxType) {
        this.taxType = taxType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tax.tax_rate
     *
     * @return the value of tax.tax_rate
     *
     * @mbggenerated
     */
    public BigDecimal getTaxRate() {
        return taxRate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tax.tax_rate
     *
     * @param taxRate the value for tax.tax_rate
     *
     * @mbggenerated
     */
    public void setTaxRate(BigDecimal taxRate) {
        this.taxRate = taxRate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tax.markup_rate
     *
     * @return the value of tax.markup_rate
     *
     * @mbggenerated
     */
    public BigDecimal getMarkupRate() {
        return markupRate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tax.markup_rate
     *
     * @param markupRate the value for tax.markup_rate
     *
     * @mbggenerated
     */
    public void setMarkupRate(BigDecimal markupRate) {
        this.markupRate = markupRate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tax.tax_number
     *
     * @return the value of tax.tax_number
     *
     * @mbggenerated
     */
    public String getTaxNumber() {
        return taxNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tax.tax_number
     *
     * @param taxNumber the value for tax.tax_number
     *
     * @mbggenerated
     */
    public void setTaxNumber(String taxNumber) {
        this.taxNumber = taxNumber == null ? null : taxNumber.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tax.tax_product_category
     *
     * @return the value of tax.tax_product_category
     *
     * @mbggenerated
     */
    public String getTaxProductCategory() {
        return taxProductCategory;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tax.tax_product_category
     *
     * @param taxProductCategory the value for tax.tax_product_category
     *
     * @mbggenerated
     */
    public void setTaxProductCategory(String taxProductCategory) {
        this.taxProductCategory = taxProductCategory == null ? null : taxProductCategory.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tax.tax_reference_amt
     *
     * @return the value of tax.tax_reference_amt
     *
     * @mbggenerated
     */
    public BigDecimal getTaxReferenceAmt() {
        return taxReferenceAmt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tax.tax_reference_amt
     *
     * @param taxReferenceAmt the value for tax.tax_reference_amt
     *
     * @mbggenerated
     */
    public void setTaxReferenceAmt(BigDecimal taxReferenceAmt) {
        this.taxReferenceAmt = taxReferenceAmt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tax.tax_reference_currency
     *
     * @return the value of tax.tax_reference_currency
     *
     * @mbggenerated
     */
    public String getTaxReferenceCurrency() {
        return taxReferenceCurrency;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tax.tax_reference_currency
     *
     * @param taxReferenceCurrency the value for tax.tax_reference_currency
     *
     * @mbggenerated
     */
    public void setTaxReferenceCurrency(String taxReferenceCurrency) {
        this.taxReferenceCurrency = taxReferenceCurrency == null ? null : taxReferenceCurrency.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tax.category_id
     *
     * @return the value of tax.category_id
     *
     * @mbggenerated
     */
    public Long getCategoryId() {
        return categoryId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tax.category_id
     *
     * @param categoryId the value for tax.category_id
     *
     * @mbggenerated
     */
    public void setCategoryId(Long categoryId) {
        this.categoryId = categoryId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tax.address_country_id
     *
     * @return the value of tax.address_country_id
     *
     * @mbggenerated
     */
    public Long getAddressCountryId() {
        return addressCountryId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tax.address_country_id
     *
     * @param addressCountryId the value for tax.address_country_id
     *
     * @mbggenerated
     */
    public void setAddressCountryId(Long addressCountryId) {
        this.addressCountryId = addressCountryId;
    }
}