package com.intramirror.main.api.model;

public class AddressCity {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column address_city.address_city_id
     *
     * @mbggenerated
     */
    private Long addressCityId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column address_city.address_province_id
     *
     * @mbggenerated
     */
    private Long addressProvinceId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column address_city.name
     *
     * @mbggenerated
     */
    private String name;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column address_city.address_city_id
     *
     * @return the value of address_city.address_city_id
     *
     * @mbggenerated
     */
    public Long getAddressCityId() {
        return addressCityId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column address_city.address_city_id
     *
     * @param addressCityId the value for address_city.address_city_id
     *
     * @mbggenerated
     */
    public void setAddressCityId(Long addressCityId) {
        this.addressCityId = addressCityId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column address_city.address_province_id
     *
     * @return the value of address_city.address_province_id
     *
     * @mbggenerated
     */
    public Long getAddressProvinceId() {
        return addressProvinceId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column address_city.address_province_id
     *
     * @param addressProvinceId the value for address_city.address_province_id
     *
     * @mbggenerated
     */
    public void setAddressProvinceId(Long addressProvinceId) {
        this.addressProvinceId = addressProvinceId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column address_city.name
     *
     * @return the value of address_city.name
     *
     * @mbggenerated
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column address_city.name
     *
     * @param name the value for address_city.name
     *
     * @mbggenerated
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }
}