package com.intramirror.main.api.model;

public class AddressCountry {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column address_country.address_country_id
     *
     * @mbggenerated
     */
    private Long addressCountryId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column address_country.name
     *
     * @mbggenerated
     */
    private String name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column address_country.geography_id
     *
     * @mbggenerated
     */
    private Long geographyId;

    private String countryCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column address_country.area_code
     *
     * @mbggenerated
     */
    private String areaCode;

    private String englishName;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column address_country.address_country_id
     *
     * @return the value of address_country.address_country_id
     *
     * @mbggenerated
     */
    public Long getAddressCountryId() {
        return addressCountryId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column address_country.address_country_id
     *
     * @param addressCountryId the value for address_country.address_country_id
     *
     * @mbggenerated
     */
    public void setAddressCountryId(Long addressCountryId) {
        this.addressCountryId = addressCountryId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column address_country.name
     *
     * @return the value of address_country.name
     *
     * @mbggenerated
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column address_country.name
     *
     * @param name the value for address_country.name
     *
     * @mbggenerated
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column address_country.geography_id
     *
     * @return the value of address_country.geography_id
     *
     * @mbggenerated
     */
    public Long getGeographyId() {
        return geographyId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column address_country.geography_id
     *
     * @param geographyId the value for address_country.geography_id
     *
     * @mbggenerated
     */
    public void setGeographyId(Long geographyId) {
        this.geographyId = geographyId;
    }

    public String getCountryCode() {
        return countryCode;
    }

    public void setCountryCode(String countryCode) {
        this.countryCode = countryCode;
    }

    public String getAreaCode() {
        return areaCode;
    }

    public void setAreaCode(String areaCode) {
        this.areaCode = areaCode;
    }

    public String getEnglishName() {
        return englishName;
    }

    public void setEnglishName(String englishName) {
        this.englishName = englishName;
    }
}