package com.intramirror.main.api.model;

public class AddressProvince {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column address_province.address_province_id
     *
     * @mbggenerated
     */
    private Long addressProvinceId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column address_province.address_country_id
     *
     * @mbggenerated
     */
    private Long addressCountryId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column address_province.name
     *
     * @mbggenerated
     */
    private String name;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column address_province.address_province_id
     *
     * @return the value of address_province.address_province_id
     *
     * @mbggenerated
     */
    public Long getAddressProvinceId() {
        return addressProvinceId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column address_province.address_province_id
     *
     * @param addressProvinceId the value for address_province.address_province_id
     *
     * @mbggenerated
     */
    public void setAddressProvinceId(Long addressProvinceId) {
        this.addressProvinceId = addressProvinceId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column address_province.address_country_id
     *
     * @return the value of address_province.address_country_id
     *
     * @mbggenerated
     */
    public Long getAddressCountryId() {
        return addressCountryId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column address_province.address_country_id
     *
     * @param addressCountryId the value for address_province.address_country_id
     *
     * @mbggenerated
     */
    public void setAddressCountryId(Long addressCountryId) {
        this.addressCountryId = addressCountryId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column address_province.name
     *
     * @return the value of address_province.name
     *
     * @mbggenerated
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column address_province.name
     *
     * @param name the value for address_province.name
     *
     * @mbggenerated
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }
}