package com.intramirror.main.api.model;

public class ApiConfiguration {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column api_configuration.api_configuration_id
     *
     * @mbggenerated
     */
    private Long apiConfigurationId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column api_configuration.vendor_id
     *
     * @mbggenerated
     */
    private Long vendorId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column api_configuration.store_code
     *
     * @mbggenerated
     */
    private String storeCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column api_configuration.api_end_point_id
     *
     * @mbggenerated
     */
    private Long apiEndPointId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column api_configuration.system
     *
     * @mbggenerated
     */
    private String system;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column api_configuration.enabled
     *
     * @mbggenerated
     */
    private Boolean enabled;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column api_configuration.api_configuration_id
     *
     * @return the value of api_configuration.api_configuration_id
     *
     * @mbggenerated
     */
    public Long getApiConfigurationId() {
        return apiConfigurationId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column api_configuration.api_configuration_id
     *
     * @param apiConfigurationId the value for api_configuration.api_configuration_id
     *
     * @mbggenerated
     */
    public void setApiConfigurationId(Long apiConfigurationId) {
        this.apiConfigurationId = apiConfigurationId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column api_configuration.vendor_id
     *
     * @return the value of api_configuration.vendor_id
     *
     * @mbggenerated
     */
    public Long getVendorId() {
        return vendorId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column api_configuration.vendor_id
     *
     * @param vendorId the value for api_configuration.vendor_id
     *
     * @mbggenerated
     */
    public void setVendorId(Long vendorId) {
        this.vendorId = vendorId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column api_configuration.store_code
     *
     * @return the value of api_configuration.store_code
     *
     * @mbggenerated
     */
    public String getStoreCode() {
        return storeCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column api_configuration.store_code
     *
     * @param storeCode the value for api_configuration.store_code
     *
     * @mbggenerated
     */
    public void setStoreCode(String storeCode) {
        this.storeCode = storeCode == null ? null : storeCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column api_configuration.api_end_point_id
     *
     * @return the value of api_configuration.api_end_point_id
     *
     * @mbggenerated
     */
    public Long getApiEndPointId() {
        return apiEndPointId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column api_configuration.api_end_point_id
     *
     * @param apiEndPointId the value for api_configuration.api_end_point_id
     *
     * @mbggenerated
     */
    public void setApiEndPointId(Long apiEndPointId) {
        this.apiEndPointId = apiEndPointId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column api_configuration.system
     *
     * @return the value of api_configuration.system
     *
     * @mbggenerated
     */
    public String getSystem() {
        return system;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column api_configuration.system
     *
     * @param system the value for api_configuration.system
     *
     * @mbggenerated
     */
    public void setSystem(String system) {
        this.system = system == null ? null : system.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column api_configuration.enabled
     *
     * @return the value of api_configuration.enabled
     *
     * @mbggenerated
     */
    public Boolean getEnabled() {
        return enabled;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column api_configuration.enabled
     *
     * @param enabled the value for api_configuration.enabled
     *
     * @mbggenerated
     */
    public void setEnabled(Boolean enabled) {
        this.enabled = enabled;
    }
}