package com.intramirror.main.api.model;

import java.math.BigDecimal;

public class ExchangeRate {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column exchange_rate.exchange_rate_id
     *
     * @mbggenerated
     */
    private Long exchangeRateId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column exchange_rate.current_rate
     *
     * @mbggenerated
     */
    private BigDecimal currentRate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column exchange_rate.from_country
     *
     * @mbggenerated
     */
    private String fromCountry;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column exchange_rate.to_country
     *
     * @mbggenerated
     */
    private String toCountry;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column exchange_rate.exchange_rate_id
     *
     * @return the value of exchange_rate.exchange_rate_id
     *
     * @mbggenerated
     */
    public Long getExchangeRateId() {
        return exchangeRateId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column exchange_rate.exchange_rate_id
     *
     * @param exchangeRateId the value for exchange_rate.exchange_rate_id
     *
     * @mbggenerated
     */
    public void setExchangeRateId(Long exchangeRateId) {
        this.exchangeRateId = exchangeRateId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column exchange_rate.current_rate
     *
     * @return the value of exchange_rate.current_rate
     *
     * @mbggenerated
     */
    public BigDecimal getCurrentRate() {
        return currentRate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column exchange_rate.current_rate
     *
     * @param currentRate the value for exchange_rate.current_rate
     *
     * @mbggenerated
     */
    public void setCurrentRate(BigDecimal currentRate) {
        this.currentRate = currentRate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column exchange_rate.from_country
     *
     * @return the value of exchange_rate.from_country
     *
     * @mbggenerated
     */
    public String getFromCountry() {
        return fromCountry;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column exchange_rate.from_country
     *
     * @param fromCountry the value for exchange_rate.from_country
     *
     * @mbggenerated
     */
    public void setFromCountry(String fromCountry) {
        this.fromCountry = fromCountry == null ? null : fromCountry.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column exchange_rate.to_country
     *
     * @return the value of exchange_rate.to_country
     *
     * @mbggenerated
     */
    public String getToCountry() {
        return toCountry;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column exchange_rate.to_country
     *
     * @param toCountry the value for exchange_rate.to_country
     *
     * @mbggenerated
     */
    public void setToCountry(String toCountry) {
        this.toCountry = toCountry == null ? null : toCountry.trim();
    }
}