package com.intramirror.main.api.model;

import java.math.BigDecimal;

public class Geography {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column geography.geography_id
     *
     * @mbggenerated
     */
    private Long geographyId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column geography.name
     *
     * @mbggenerated
     */
    private String name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column geography.ship_fee
     *
     * @mbggenerated
     */
    private BigDecimal shipFee;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column geography.tax_fee
     *
     * @mbggenerated
     */
    private BigDecimal taxFee;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column geography.display_order
     *
     * @mbggenerated
     */
    private Integer displayOrder;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column geography.english_name
     *
     * @mbggenerated
     */
    private String englishName;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column geography.geography_id
     *
     * @return the value of geography.geography_id
     *
     * @mbggenerated
     */
    public Long getGeographyId() {
        return geographyId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column geography.geography_id
     *
     * @param geographyId the value for geography.geography_id
     *
     * @mbggenerated
     */
    public void setGeographyId(Long geographyId) {
        this.geographyId = geographyId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column geography.name
     *
     * @return the value of geography.name
     *
     * @mbggenerated
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column geography.name
     *
     * @param name the value for geography.name
     *
     * @mbggenerated
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column geography.ship_fee
     *
     * @return the value of geography.ship_fee
     *
     * @mbggenerated
     */
    public BigDecimal getShipFee() {
        return shipFee;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column geography.ship_fee
     *
     * @param shipFee the value for geography.ship_fee
     *
     * @mbggenerated
     */
    public void setShipFee(BigDecimal shipFee) {
        this.shipFee = shipFee;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column geography.tax_fee
     *
     * @return the value of geography.tax_fee
     *
     * @mbggenerated
     */
    public BigDecimal getTaxFee() {
        return taxFee;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column geography.tax_fee
     *
     * @param taxFee the value for geography.tax_fee
     *
     * @mbggenerated
     */
    public void setTaxFee(BigDecimal taxFee) {
        this.taxFee = taxFee;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column geography.display_order
     *
     * @return the value of geography.display_order
     *
     * @mbggenerated
     */
    public Integer getDisplayOrder() {
        return displayOrder;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column geography.display_order
     *
     * @param displayOrder the value for geography.display_order
     *
     * @mbggenerated
     */
    public void setDisplayOrder(Integer displayOrder) {
        this.displayOrder = displayOrder;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column geography.english_name
     *
     * @return the value of geography.english_name
     *
     * @mbggenerated
     */
    public String getEnglishName() {
        return englishName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column geography.english_name
     *
     * @param englishName the value for geography.english_name
     *
     * @mbggenerated
     */
    public void setEnglishName(String englishName) {
        this.englishName = englishName == null ? null : englishName.trim();
    }
}