package com.intramirror.main.api.model;

public class PostCode {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column post_code.post_code_id
     *
     * @mbggenerated
     */
    private Long postCodeId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column post_code.country_id
     *
     * @mbggenerated
     */
    private Long countryId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column post_code.country_code
     *
     * @mbggenerated
     */
    private String countryCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column post_code.city_name
     *
     * @mbggenerated
     */
    private String cityName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column post_code.zip_low
     *
     * @mbggenerated
     */
    private String zipLow;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column post_code.zip_high
     *
     * @mbggenerated
     */
    private String zipHigh;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column post_code.post_code_id
     *
     * @return the value of post_code.post_code_id
     *
     * @mbggenerated
     */
    public Long getPostCodeId() {
        return postCodeId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column post_code.post_code_id
     *
     * @param postCodeId the value for post_code.post_code_id
     *
     * @mbggenerated
     */
    public void setPostCodeId(Long postCodeId) {
        this.postCodeId = postCodeId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column post_code.country_id
     *
     * @return the value of post_code.country_id
     *
     * @mbggenerated
     */
    public Long getCountryId() {
        return countryId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column post_code.country_id
     *
     * @param countryId the value for post_code.country_id
     *
     * @mbggenerated
     */
    public void setCountryId(Long countryId) {
        this.countryId = countryId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column post_code.country_code
     *
     * @return the value of post_code.country_code
     *
     * @mbggenerated
     */
    public String getCountryCode() {
        return countryCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column post_code.country_code
     *
     * @param countryCode the value for post_code.country_code
     *
     * @mbggenerated
     */
    public void setCountryCode(String countryCode) {
        this.countryCode = countryCode == null ? null : countryCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column post_code.city_name
     *
     * @return the value of post_code.city_name
     *
     * @mbggenerated
     */
    public String getCityName() {
        return cityName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column post_code.city_name
     *
     * @param cityName the value for post_code.city_name
     *
     * @mbggenerated
     */
    public void setCityName(String cityName) {
        this.cityName = cityName == null ? null : cityName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column post_code.zip_low
     *
     * @return the value of post_code.zip_low
     *
     * @mbggenerated
     */
    public String getZipLow() {
        return zipLow;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column post_code.zip_low
     *
     * @param zipLow the value for post_code.zip_low
     *
     * @mbggenerated
     */
    public void setZipLow(String zipLow) {
        this.zipLow = zipLow == null ? null : zipLow.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column post_code.zip_high
     *
     * @return the value of post_code.zip_high
     *
     * @mbggenerated
     */
    public String getZipHigh() {
        return zipHigh;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column post_code.zip_high
     *
     * @param zipHigh the value for post_code.zip_high
     *
     * @mbggenerated
     */
    public void setZipHigh(String zipHigh) {
        this.zipHigh = zipHigh == null ? null : zipHigh.trim();
    }
}