package com.intramirror.main.api.model;

import java.util.Date;

public class StockLocation {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column stock_location.location_id
     *
     * @mbggenerated
     */
    private Long locationId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column stock_location.stock_location
     *
     * @mbggenerated
     */
    private String stockLocation;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column stock_location.vendor_id
     *
     * @mbggenerated
     */
    private Long vendorId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column stock_location.create_at
     *
     * @mbggenerated
     */
    private Date createAt;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column stock_location.update_at
     *
     * @mbggenerated
     */
    private Date updateAt;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column stock_location.enabled
     *
     * @mbggenerated
     */
    private Boolean enabled;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column stock_location.location_id
     *
     * @return the value of stock_location.location_id
     *
     * @mbggenerated
     */
    public Long getLocationId() {
        return locationId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column stock_location.location_id
     *
     * @param locationId the value for stock_location.location_id
     *
     * @mbggenerated
     */
    public void setLocationId(Long locationId) {
        this.locationId = locationId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column stock_location.stock_location
     *
     * @return the value of stock_location.stock_location
     *
     * @mbggenerated
     */
    public String getStockLocation() {
        return stockLocation;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column stock_location.stock_location
     *
     * @param stockLocation the value for stock_location.stock_location
     *
     * @mbggenerated
     */
    public void setStockLocation(String stockLocation) {
        this.stockLocation = stockLocation == null ? null : stockLocation.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column stock_location.vendor_id
     *
     * @return the value of stock_location.vendor_id
     *
     * @mbggenerated
     */
    public Long getVendorId() {
        return vendorId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column stock_location.vendor_id
     *
     * @param vendorId the value for stock_location.vendor_id
     *
     * @mbggenerated
     */
    public void setVendorId(Long vendorId) {
        this.vendorId = vendorId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column stock_location.create_at
     *
     * @return the value of stock_location.create_at
     *
     * @mbggenerated
     */
    public Date getCreateAt() {
        return createAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column stock_location.create_at
     *
     * @param createAt the value for stock_location.create_at
     *
     * @mbggenerated
     */
    public void setCreateAt(Date createAt) {
        this.createAt = createAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column stock_location.update_at
     *
     * @return the value of stock_location.update_at
     *
     * @mbggenerated
     */
    public Date getUpdateAt() {
        return updateAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column stock_location.update_at
     *
     * @param updateAt the value for stock_location.update_at
     *
     * @mbggenerated
     */
    public void setUpdateAt(Date updateAt) {
        this.updateAt = updateAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column stock_location.enabled
     *
     * @return the value of stock_location.enabled
     *
     * @mbggenerated
     */
    public Boolean getEnabled() {
        return enabled;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column stock_location.enabled
     *
     * @param enabled the value for stock_location.enabled
     *
     * @mbggenerated
     */
    public void setEnabled(Boolean enabled) {
        this.enabled = enabled;
    }
}