package pk.shoplus.thirdpart.wintopay;

public class Country {
	public static final String CHNCN = "CHNCN";
	public static final String AFGAF = "AFGAF";
	public static final String ALBAL = "ALBAL";
	public static final String ANDAD = "ANDAD";
	public static final String AGOAI = "AGOAI";
	public static final String ARMAM = "ARMAM";
	public static final String ABWAW = "ABWAW";
	public static final String AUSAU = "AUSAU";
	public static final String AREAE = "AREAE";
	public static final String ARGAR = "ARGAR";
	public static final String ATGAG = "ATGAG";
	public static final String AUTAT = "AUTAT";
	public static final String AZEAZ = "AZEAZ";
	public static final String ANTAN = "ANTAN";
	public static final String BRBBB = "BRBBB";
	public static final String BGDBD = "BGDBD";
	public static final String BELBE = "BELBE";
	public static final String BLZBZ = "BLZBZ";
	public static final String BENBJ = "BENBJ";
	public static final String BTNBT = "BTNBT";
	public static final String BOLBO = "BOLBO";
	public static final String BIHBA = "BIHBA";
	public static final String BWABW = "BWABW";
	public static final String BRNBN = "BRNBN";
	public static final String BGRBG = "BGRBG";
	public static final String BHRBH = "BHRBH";
	public static final String BMUBM = "BMUBM";
	public static final String BRABR = "BRABR";
	public static final String BHSBS = "BHSBS";
	public static final String BFABF = "BFABF";
	public static final String BDIBI = "BDIBI";
	public static final String CMRCM = "CMRCM";
	public static final String CANCA = "CANCA";
	public static final String CPVCV = "CPVCV";
	public static final String CAFCF = "CAFCF";
	public static final String COMKM = "COMKM";
	public static final String COGCG = "COGCG";
	public static final String CHECH = "CHECH";
	public static final String CHLCL = "CHLCL";
	public static final String COLCO = "COLCO";
	public static final String CRICR = "CRICR";
	public static final String CYPCY = "CYPCY";
	public static final String CZECZ = "CZECZ";
	public static final String DEUDE = "DEUDE";
	public static final String DNKDK = "DNKDK";
	public static final String DJIDJ = "DJIDJ";
	public static final String DZADZ = "DZADZ";
	public static final String DOMDO = "DOMDO";
	public static final String ECUEC = "ECUEC";
	public static final String EGYEG = "EGYEG";
	public static final String ERIER = "ERIER";
	public static final String ESTEE = "ESTEE";
	public static final String ETHET = "ETHET";
	public static final String ESPES = "ESPES";
	public static final String ESHEH = "ESHEH";
	public static final String FJIFJ = "FJIFJ";
	public static final String FRAFR = "FRAFR";
	public static final String FINFI = "FINFI";
	public static final String GUFGF = "GUFGF";
	public static final String GABGA = "GABGA";
	public static final String GMBGM = "GMBGM";
	public static final String GEOGE = "GEOGE";
	public static final String GHAGH = "GHAGH";
	public static final String GIBGI = "GIBGI";
	public static final String GRDGD = "GRDGD";
	public static final String GRCGR = "GRCGR";
	public static final String GLPGP = "GLPGP";
	public static final String GTMGT = "GTMGT";
	public static final String GUYGY = "GUYGY";
	public static final String GNBGW = "GNBGW";
	public static final String GBRGB = "GBRGB";
	public static final String HTIHT = "HTIHT";
	public static final String HNDHN = "HNDHN";
	public static final String HKGHK = "HKGHK";
	public static final String HUNHU = "HUNHU";
	public static final String INAID = "INAID";
	public static final String IRLIE = "IRLIE";
	public static final String ISRIL = "ISRIL";
	public static final String INDIN = "INDIN";
	public static final String ISLIS = "ISLIS";
	public static final String ITAIT = "ITAIT";
	public static final String JAMJM = "JAMJM";
	public static final String JPNJP = "JPNJP";
	public static final String JORJO = "JORJO";
	public static final String KAZKZ = "KAZKZ";
	public static final String KENKE = "KENKE";
	public static final String KGZKG = "KGZKG";
	public static final String KORKR = "KORKR";
	public static final String KWTKW = "KWTKW";
	public static final String KNAKN = "KNAKN";
	public static final String LBNLB = "LBNLB";
	public static final String LBYLY = "LBYLY";
	public static final String LIELI = "LIELI";
	public static final String LKALK = "LKALK";
	public static final String LTULT = "LTULT";
	public static final String LUXLU = "LUXLU";
	public static final String LVALV = "LVALV";
	public static final String LCALC = "LCALC";
	public static final String MCOMC = "MCOMC";
	public static final String MACMO = "MACMO";
	public static final String MKDMk = "MKDMk";
	public static final String MDGMG = "MDGMG";
	public static final String MWIMW = "MWIMW";
	public static final String MDVMV = "MDVMV";
	public static final String MLIML = "MLIML";
	public static final String MLTMT = "MLTMT";
	public static final String MTQMQ = "MTQMQ";
	public static final String MRTMR = "MRTMR";
	public static final String MUSMU = "MUSMU";
	public static final String MEXME = "MEXME";
	public static final String MYSMY = "MYSMY";
	public static final String MDAMD = "MDAMD";
	public static final String MNGMN = "MNGMN";
	public static final String MARMA = "MARMA";
	public static final String MOZMZ = "MOZMZ";
	public static final String NAMNA = "NAMNA";
	public static final String NPLNP = "NPLNP";
	public static final String NLDNL = "NLDNL";
	public static final String NICNI = "NICNI";
	public static final String NERNE = "NERNE";
	public static final String NGANG = "NGANG";
	public static final String NORNO = "NORNO";
	public static final String NZLNZ = "NZLNZ";
	public static final String OMNOM = "OMNOM";
	public static final String PAKPK = "PAKPK";
	public static final String PANPA = "PANPA";
	public static final String PNGPG = "PNGPG";
	public static final String PRYPY = "PRYPY";
	public static final String PERPE = "PERPE";
	public static final String PHLPH = "PHLPH";
	public static final String POLPL = "POLPL";
	public static final String PRTPT = "PRTPT";
	public static final String QATQA = "QATQA";
	public static final String ROURO = "ROURO";
	public static final String RUSRU = "RUSRU";
	public static final String RWARW = "RWARW";
	public static final String SMRSM = "SMRSM";
	public static final String STPST = "STPST";
	public static final String SAUSA = "SAUSA";
	public static final String SENSN = "SENSN";
	public static final String SRBRS = "SRBRS";
	public static final String SWZSZ = "SWZSZ";
	public static final String SYCSC = "SYCSC";
	public static final String SLESL = "SLESL";
	public static final String SOMSO = "SOMSO";
	public static final String SURSR = "SURSR";
	public static final String SWESW = "SWESW";
	public static final String SGPSG = "SGPSG";
	public static final String SVKSK = "SVKSK";
	public static final String SVNSI = "SVNSI";
	public static final String SLVSV = "SLVSV";
	public static final String SYRSY = "SYRSY";
	public static final String TJKTJ = "TJKTJ";
	public static final String TZATZ = "TZATZ";
	public static final String THATH = "THATH";
	public static final String TGOTG = "TGOTG";
	public static final String TUNTN = "TUNTN";
	public static final String TURTR = "TURTR";
	public static final String TTOTT = "TTOTT";
	public static final String TWNTW = "TWNTW";
	public static final String TKMTM = "TKMTM";
	public static final String TCATC = "TCATC";
	public static final String UGAUG = "UGAUG";
	public static final String UKRUA = "UKRUA";
	public static final String USAUS = "USAUS";
	public static final String URYUY = "URYUY";
	public static final String UZBUZ = "UZBUZ";
	public static final String VENVE = "VENVE";
	public static final String VCTVC = "VCTVC";
	public static final String VNMVN = "VNMVN";
	public static final String YEMYE = "YEMYE";
	public static final String ZMBZM = "ZMBZM";
	public static final String ZAFZA = "ZAFZA";
}

/*
<optionvalue="CHNCN">China</option>
<optionvalue="AFGAF">Afghanistan</option>
<optionvalue="ALBAL">Albania</option>
<optionvalue="ANDAD">Andorra</option>
<optionvalue="AGOAI">Angola</option>
<optionvalue="ARMAM">Armenia</option>
<optionvalue="ABWAW">Aruba</option>
<optionvalue="AUSAU">Australia</option>
<optionvalue="AREAE">United Arab Emirates</option>
<optionvalue="ARGAR">Argentina</option>
<optionvalue="ATGAG">Antigua and Barbuda</option>
<optionvalue="AUTAT">Austria</option>
<optionvalue="AZEAZ">Azerbaijan</option>
<optionvalue="ANTAN">Netherlands Antilles</option>
<optionvalue="BRBBB">Barbados</option>
<optionvalue="BGDBD">Bangladesh</option>
<optionvalue="BELBE">Belgium</option>
<optionvalue="BLZBZ">Belize</option>
<optionvalue="BENBJ">Benin</option>
<optionvalue="BTNBT">Bhutan</option>
<optionvalue="BOLBO">Bolivia</option>
<optionvalue="BIHBA">Bosnia and Herzegovina</option>
<optionvalue="BWABW">Botswana</option>
<optionvalue="BRNBN">Brunei</option>
<optionvalue="BGRBG">Bulgaria</option>
<optionvalue="BHRBH">Bahrain</option>
<optionvalue="BMUBM">Bermuda</option>
<optionvalue="BRABR">Brazil</option>
<optionvalue="BHSBS">Bahamas</option>
<optionvalue="BFABF">Burkina Faso</option>
<optionvalue="BDIBI">Burundi</option>
<optionvalue="CMRCM">Cameroon</option>
<optionvalue="CANCA">Canada</option>
<optionvalue="CPVCV">Cape Verde</option>
<optionvalue="CAFCF">Central African Republic</option>
<optionvalue="COMKM">Comoros</option>
<optionvalue="COGCG">Congo</option>
<optionvalue="CHECH">Switzerland</option>
<optionvalue="CHLCL">Chile</option>
<optionvalue="COLCO">Colombia</option>
<optionvalue="CRICR">Costa Rica</option>
<optionvalue="CYPCY">Cyprus</option>
<optionvalue="CZECZ">Czech Republic</option>
<optionvalue="DEUDE">Germany</option>
<optionvalue="DNKDK">Denmark</option>
<optionvalue="DJIDJ">Djibouti</option>
<optionvalue="DZADZ">Algeria</option>
<optionvalue="DOMDO">Dominican Republic</option>
<optionvalue="ECUEC">Ecuador</option>
<optionvalue="EGYEG">Egypt</option>
<optionvalue="ERIER">Eritrea</option>
<optionvalue="ESTEE">Estonia</option>
<optionvalue="ETHET">Ethiopia</option>
<optionvalue="ESPES">Spain</option>
<optionvalue="ESHEH">Western Sahara</option>
<optionvalue="FJIFJ">Fiji</option>
<optionvalue="FRAFR">France</option>
<optionvalue="FINFI">Finland</option>
<optionvalue="GUFGF">French Guiana</option>
<optionvalue="GABGA">Gabon</option>
<optionvalue="GMBGM">Gambia</option>
<optionvalue="GEOGE">Georgia</option>
<optionvalue="GHAGH">Ghana</option>
<optionvalue="GIBGI">Gibraltar</option>
<optionvalue="GRDGD">Grenada</option>
<optionvalue="GRCGR">Greece</option>
<optionvalue="GLPGP">Guadeloupe</option>
<optionvalue="GTMGT">Guatemala</option>
<optionvalue="GUYGY">Guyana</option>
<optionvalue="GNBGW">Guinea-Bissau</option>
<optionvalue="GBRGB">United Kingdom</option>
<optionvalue="HTIHT">Haiti</option>
<optionvalue="HNDHN">Honduras</option>
<optionvalue="HKGHK">Hong Kong</option>
<optionvalue="HUNHU">Hungary</option>
<optionvalue="INAID">The Republic of Indonesia</option>
<optionvalue="IRLIE">Ireland</option>
<optionvalue="ISRIL">Israel</option>
<optionvalue="INDIN">India</option>
<optionvalue="ISLIS">Iceland</option>
<optionvalue="ITAIT">Italy</option>
<optionvalue="JAMJM">Jamaica</option>
<optionvalue="JPNJP">Japan</option>
<optionvalue="JORJO">Jordan</option>
<optionvalue="KAZKZ">Kazakhstan</option>
<optionvalue="KENKE">Kenya</option>
<optionvalue="KGZKG">Kyrgyzstan</option>
<optionvalue="KORKR">Korea</option>
<optionvalue="KWTKW">Kuwait</option>
<optionvalue="KNAKN">Saint Kitts and Nevis</option>
<optionvalue="LBNLB">Lebanon</option>
<optionvalue="LBYLY">Libyan Arab Jamahiriya</option>
<optionvalue="LIELI">Liechtenstein</option>
<optionvalue="LKALK">Sri Lanka</option>
<optionvalue="LTULT">Lithuania</option>
<optionvalue="LUXLU">Luxembourg</option>
<optionvalue="LVALV">Latvia</option>
<optionvalue="LCALC">Saint Lucia</option>
<optionvalue="MCOMC">Monaco</option>
<optionvalue="MACMO">Macau</option>
<optionvalue="MKDMk">Macedonia</option>
<optionvalue="MDGMG">Madagascar</option>
<optionvalue="MWIMW">Malawi</option>
<optionvalue="MDVMV">Maldives</option>
<optionvalue="MLIML">Mali</option>
<optionvalue="MLTMT">Malta</option>
<optionvalue="MTQMQ">Martinique</option>
<optionvalue="MRTMR">Mauritania</option>
<optionvalue="MUSMU">Mauritius</option>
<optionvalue="MEXME">Mexico</option>
<optionvalue="MYSMY">Malaysia</option>
<optionvalue="MDAMD">Moldova</option>
<optionvalue="MNGMN">Mongolia</option>
<optionvalue="MARMA">Morocco</option>
<optionvalue="MOZMZ">Mozambique</option>
<optionvalue="NAMNA">Namibia</option>
<optionvalue="NPLNP">Nepal</option>
<optionvalue="NLDNL">Netherlands</option>
<optionvalue="NICNI">Nicaragua</option>
<optionvalue="NERNE">Niger</option>
<optionvalue="NGANG">Nigeria</option>
<optionvalue="NORNO">Norway</option>
<optionvalue="NZLNZ">New Zealand</option>
<optionvalue="OMNOM">Oman</option>
<optionvalue="PAKPK">Pakistan</option>
<optionvalue="PANPA">Panama</option>
<optionvalue="PNGPG">Papua New Guinea</option>
<optionvalue="PRYPY">Paraguay</option>
<optionvalue="PERPE">Peru</option>
<optionvalue="PHLPH">Philippines</option>
<optionvalue="POLPL">Poland</option>
<optionvalue="PRTPT">Portugal</option>
<optionvalue="QATQA">Qatar</option>
<optionvalue="ROURO">Romania</option>
<optionvalue="RUSRU">Russian Federation</option>
<optionvalue="RWARW">Rwanda</option>
<optionvalue="SMRSM">San Marino</option>
<optionvalue="STPST">Sao Tome and Principe</option>
<optionvalue="SAUSA">Saudi Arabia</option>
<optionvalue="SENSN">Senegal</option>
<optionvalue="SRBRS">Serbia</option>
<optionvalue="SWZSZ">Swaziland</option>
<optionvalue="SYCSC">Seychelles</option>
<optionvalue="SLESL">Sierra Leone</option>
<optionvalue="SOMSO">Somalia</option>
<optionvalue="SURSR">Suriname</option>
<optionvalue="SWESW">Sweden</option>
<optionvalue="SGPSG">Singapore</option>
<optionvalue="SVKSK">Slovakia</option>
<optionvalue="SVNSI">Slovenia</option>
<optionvalue="SLVSV">El Salvador</option>
<optionvalue="SYRSY">Syrian Arab Republic</option>
<optionvalue="TJKTJ">Tajikistan</option>
<optionvalue="TZATZ">Tanzania</option>
<optionvalue="THATH">Thailand</option>
<optionvalue="TGOTG">Togo</option>
<optionvalue="TUNTN">Tunisia</option>
<optionvalue="TURTR">Turkey</option>
<optionvalue="TTOTT">Trinidad and Tobago</option>
<optionvalue="TWNTW">Taiwan, Province of China</option>
<optionvalue="TKMTM">Turkmenistan</option>
<optionvalue="TCATC">Turks and Caicos Islands</option>
<optionvalue="UGAUG">Uganda</option>
<optionvalue="UKRUA">Ukraine</option>
<optionvalue="USAUS">United States</option>
<optionvalue="URYUY">Uruguay</option>
<optionvalue="UZBUZ">Uzbekistan</option>
<optionvalue="VENVE">Venezuela</option>
<optionvalue="VCTVC">Saint Vincent and the Grenadines</option>
<optionvalue="VNMVN">Vietnam</option>
<optionvalue="YEMYE">Yemen</option>
<optionvalue="ZMBZM">Zambia</option>
<optionvalue="ZAFZA">South Africa</option>
*/