package com.intramirror.payment.core.mapper;

import com.intramirror.payment.api.model.PaymentResult;

public interface PaymentResultMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table payment_result
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Long paymentResultId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table payment_result
     *
     * @mbggenerated
     */
    int insert(PaymentResult record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table payment_result
     *
     * @mbggenerated
     */
    int insertSelective(PaymentResult record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table payment_result
     *
     * @mbggenerated
     */
    PaymentResult selectByPrimaryKey(Long paymentResultId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table payment_result
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(PaymentResult record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table payment_result
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(PaymentResult record);
}