package com.intramirror.common.core.mapper;

import com.intramirror.order.api.model.ThirdWarehouse;
import com.intramirror.order.api.model.ThirdWarehouseExample;
import org.apache.ibatis.annotations.Param;

import java.util.List;

public interface ThirdWarehouseMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table third_warehouse
     *
     * @mbg.generated
     */
    long countByExample(ThirdWarehouseExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table third_warehouse
     *
     * @mbg.generated
     */
    int insert(ThirdWarehouse record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table third_warehouse
     *
     * @mbg.generated
     */
    int insertSelective(ThirdWarehouse record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table third_warehouse
     *
     * @mbg.generated
     */
    List<ThirdWarehouse> selectByExample(ThirdWarehouseExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table third_warehouse
     *
     * @mbg.generated
     */
    ThirdWarehouse selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table third_warehouse
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") ThirdWarehouse record, @Param("example") ThirdWarehouseExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table third_warehouse
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") ThirdWarehouse record, @Param("example") ThirdWarehouseExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table third_warehouse
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(ThirdWarehouse record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table third_warehouse
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(ThirdWarehouse record);

    List<ThirdWarehouse> getOrderDetailList(String shipmentNo);
}