package com.intramirror.common.core.mapper;

import com.intramirror.order.api.model.TransitWarehouse;


public interface TransitWarehouseMapper {

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table transit_warehouse
     *
     * @mbg.generated
     */
    int insert(TransitWarehouse record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table transit_warehouse
     *
     * @mbg.generated
     */
    int insertSelective(TransitWarehouse record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table transit_warehouse
     *
     * @mbg.generated
     */
    TransitWarehouse selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table transit_warehouse
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(TransitWarehouse record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table transit_warehouse
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(TransitWarehouse record);
}