package com.intramirror.common.api.model;

public class ShippingSegment {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column shipping_segment.shipping_segment_id
     *
     * @mbggenerated
     */
    private Long shippingSegmentId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column shipping_segment.segment_sequence
     *
     * @mbggenerated
     */
    private Long segmentSequence;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column shipping_segment.shipping_routing_id
     *
     * @mbggenerated
     */
    private Long shippingRoutingId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column shipping_segment.shipping_provider_id
     *
     * @mbggenerated
     */
    private Long shippingProviderId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column shipping_segment.shipment_type_id
     *
     * @mbggenerated
     */
    private Long shipmentTypeId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column shipping_segment.shipping_segment_id
     *
     * @return the value of shipping_segment.shipping_segment_id
     *
     * @mbggenerated
     */
    public Long getShippingSegmentId() {
        return shippingSegmentId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column shipping_segment.shipping_segment_id
     *
     * @param shippingSegmentId the value for shipping_segment.shipping_segment_id
     *
     * @mbggenerated
     */
    public void setShippingSegmentId(Long shippingSegmentId) {
        this.shippingSegmentId = shippingSegmentId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column shipping_segment.segment_sequence
     *
     * @return the value of shipping_segment.segment_sequence
     *
     * @mbggenerated
     */
    public Long getSegmentSequence() {
        return segmentSequence;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column shipping_segment.segment_sequence
     *
     * @param segmentSequence the value for shipping_segment.segment_sequence
     *
     * @mbggenerated
     */
    public void setSegmentSequence(Long segmentSequence) {
        this.segmentSequence = segmentSequence;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column shipping_segment.shipping_routing_id
     *
     * @return the value of shipping_segment.shipping_routing_id
     *
     * @mbggenerated
     */
    public Long getShippingRoutingId() {
        return shippingRoutingId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column shipping_segment.shipping_routing_id
     *
     * @param shippingRoutingId the value for shipping_segment.shipping_routing_id
     *
     * @mbggenerated
     */
    public void setShippingRoutingId(Long shippingRoutingId) {
        this.shippingRoutingId = shippingRoutingId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column shipping_segment.shipping_provider_id
     *
     * @return the value of shipping_segment.shipping_provider_id
     *
     * @mbggenerated
     */
    public Long getShippingProviderId() {
        return shippingProviderId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column shipping_segment.shipping_provider_id
     *
     * @param shippingProviderId the value for shipping_segment.shipping_provider_id
     *
     * @mbggenerated
     */
    public void setShippingProviderId(Long shippingProviderId) {
        this.shippingProviderId = shippingProviderId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column shipping_segment.shipment_type_id
     *
     * @return the value of shipping_segment.shipment_type_id
     *
     * @mbggenerated
     */
    public Long getShipmentTypeId() {
        return shipmentTypeId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column shipping_segment.shipment_type_id
     *
     * @param shipmentTypeId the value for shipping_segment.shipment_type_id
     *
     * @mbggenerated
     */
    public void setShipmentTypeId(Long shipmentTypeId) {
        this.shipmentTypeId = shipmentTypeId;
    }
}