package com.intramirror.product.api.model;

public class ApiMq {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column api_mq.api_mq_id
     *
     * @mbggenerated
     */
    private Long apiMqId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column api_mq.api_configuration_id
     *
     * @mbggenerated
     */
    private Long apiConfigurationId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column api_mq.name
     *
     * @mbggenerated
     */
    private String name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column api_mq.enabled
     *
     * @mbggenerated
     */
    private Boolean enabled;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column api_mq.api_mq_id
     *
     * @return the value of api_mq.api_mq_id
     *
     * @mbggenerated
     */
    public Long getApiMqId() {
        return apiMqId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column api_mq.api_mq_id
     *
     * @param apiMqId the value for api_mq.api_mq_id
     *
     * @mbggenerated
     */
    public void setApiMqId(Long apiMqId) {
        this.apiMqId = apiMqId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column api_mq.api_configuration_id
     *
     * @return the value of api_mq.api_configuration_id
     *
     * @mbggenerated
     */
    public Long getApiConfigurationId() {
        return apiConfigurationId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column api_mq.api_configuration_id
     *
     * @param apiConfigurationId the value for api_mq.api_configuration_id
     *
     * @mbggenerated
     */
    public void setApiConfigurationId(Long apiConfigurationId) {
        this.apiConfigurationId = apiConfigurationId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column api_mq.name
     *
     * @return the value of api_mq.name
     *
     * @mbggenerated
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column api_mq.name
     *
     * @param name the value for api_mq.name
     *
     * @mbggenerated
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column api_mq.enabled
     *
     * @return the value of api_mq.enabled
     *
     * @mbggenerated
     */
    public Boolean getEnabled() {
        return enabled;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column api_mq.enabled
     *
     * @param enabled the value for api_mq.enabled
     *
     * @mbggenerated
     */
    public void setEnabled(Boolean enabled) {
        this.enabled = enabled;
    }
}