package com.intramirror.product.api.model;

import java.util.Date;

public class BlockTagRel {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column block_tag_rel.blockTagId
     *
     * @mbggenerated
     */
    private Long blockTagId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column block_tag_rel.tag_id
     *
     * @mbggenerated
     */
    private Long tagId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column block_tag_rel.block_id
     *
     * @mbggenerated
     */
    private Long blockId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column block_tag_rel.create_at
     *
     * @mbggenerated
     */
    private Date createAt;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column block_tag_rel.blockTagId
     *
     * @return the value of block_tag_rel.blockTagId
     *
     * @mbggenerated
     */
    public Long getBlockTagId() {
        return blockTagId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column block_tag_rel.blockTagId
     *
     * @param blockTagId the value for block_tag_rel.blockTagId
     *
     * @mbggenerated
     */
    public void setBlockTagId(Long blockTagId) {
        this.blockTagId = blockTagId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column block_tag_rel.tag_id
     *
     * @return the value of block_tag_rel.tag_id
     *
     * @mbggenerated
     */
    public Long getTagId() {
        return tagId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column block_tag_rel.tag_id
     *
     * @param tagId the value for block_tag_rel.tag_id
     *
     * @mbggenerated
     */
    public void setTagId(Long tagId) {
        this.tagId = tagId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column block_tag_rel.block_id
     *
     * @return the value of block_tag_rel.block_id
     *
     * @mbggenerated
     */
    public Long getBlockId() {
        return blockId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column block_tag_rel.block_id
     *
     * @param blockId the value for block_tag_rel.block_id
     *
     * @mbggenerated
     */
    public void setBlockId(Long blockId) {
        this.blockId = blockId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column block_tag_rel.create_at
     *
     * @return the value of block_tag_rel.create_at
     *
     * @mbggenerated
     */
    public Date getCreateAt() {
        return createAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column block_tag_rel.create_at
     *
     * @param createAt the value for block_tag_rel.create_at
     *
     * @mbggenerated
     */
    public void setCreateAt(Date createAt) {
        this.createAt = createAt;
    }
}