package com.intramirror.product.api.model;

import java.util.Date;

public class Brand {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column brand.brand_id
     *
     * @mbggenerated
     */
    private Long brandId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column brand.english_name
     *
     * @mbggenerated
     */
    private String englishName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column brand.chinese_name
     *
     * @mbggenerated
     */
    private String chineseName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column brand.logo
     *
     * @mbggenerated
     */
    private String logo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column brand.type
     *
     * @mbggenerated
     */
    private Byte type;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column brand.remark
     *
     * @mbggenerated
     */
    private String remark;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column brand.creator
     *
     * @mbggenerated
     */
    private String creator;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column brand.created_at
     *
     * @mbggenerated
     */
    private Date createdAt;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column brand.updated_at
     *
     * @mbggenerated
     */
    private Date updatedAt;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column brand.enabled
     *
     * @mbggenerated
     */
    private Boolean enabled;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column brand.status
     *
     * @mbggenerated
     */
    private Byte status;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column brand.vendor_application_id
     *
     * @mbggenerated
     */
    private Long vendorApplicationId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column brand.hot_brand
     *
     * @mbggenerated
     */
    private Integer hotBrand;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column brand.description
     *
     * @mbggenerated
     */
    private String description;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column brand.brand_id
     *
     * @return the value of brand.brand_id
     *
     * @mbggenerated
     */
    public Long getBrandId() {
        return brandId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column brand.brand_id
     *
     * @param brandId the value for brand.brand_id
     *
     * @mbggenerated
     */
    public void setBrandId(Long brandId) {
        this.brandId = brandId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column brand.english_name
     *
     * @return the value of brand.english_name
     *
     * @mbggenerated
     */
    public String getEnglishName() {
        return englishName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column brand.english_name
     *
     * @param englishName the value for brand.english_name
     *
     * @mbggenerated
     */
    public void setEnglishName(String englishName) {
        this.englishName = englishName == null ? null : englishName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column brand.chinese_name
     *
     * @return the value of brand.chinese_name
     *
     * @mbggenerated
     */
    public String getChineseName() {
        return chineseName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column brand.chinese_name
     *
     * @param chineseName the value for brand.chinese_name
     *
     * @mbggenerated
     */
    public void setChineseName(String chineseName) {
        this.chineseName = chineseName == null ? null : chineseName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column brand.logo
     *
     * @return the value of brand.logo
     *
     * @mbggenerated
     */
    public String getLogo() {
        return logo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column brand.logo
     *
     * @param logo the value for brand.logo
     *
     * @mbggenerated
     */
    public void setLogo(String logo) {
        this.logo = logo == null ? null : logo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column brand.type
     *
     * @return the value of brand.type
     *
     * @mbggenerated
     */
    public Byte getType() {
        return type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column brand.type
     *
     * @param type the value for brand.type
     *
     * @mbggenerated
     */
    public void setType(Byte type) {
        this.type = type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column brand.remark
     *
     * @return the value of brand.remark
     *
     * @mbggenerated
     */
    public String getRemark() {
        return remark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column brand.remark
     *
     * @param remark the value for brand.remark
     *
     * @mbggenerated
     */
    public void setRemark(String remark) {
        this.remark = remark == null ? null : remark.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column brand.creator
     *
     * @return the value of brand.creator
     *
     * @mbggenerated
     */
    public String getCreator() {
        return creator;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column brand.creator
     *
     * @param creator the value for brand.creator
     *
     * @mbggenerated
     */
    public void setCreator(String creator) {
        this.creator = creator == null ? null : creator.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column brand.created_at
     *
     * @return the value of brand.created_at
     *
     * @mbggenerated
     */
    public Date getCreatedAt() {
        return createdAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column brand.created_at
     *
     * @param createdAt the value for brand.created_at
     *
     * @mbggenerated
     */
    public void setCreatedAt(Date createdAt) {
        this.createdAt = createdAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column brand.updated_at
     *
     * @return the value of brand.updated_at
     *
     * @mbggenerated
     */
    public Date getUpdatedAt() {
        return updatedAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column brand.updated_at
     *
     * @param updatedAt the value for brand.updated_at
     *
     * @mbggenerated
     */
    public void setUpdatedAt(Date updatedAt) {
        this.updatedAt = updatedAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column brand.enabled
     *
     * @return the value of brand.enabled
     *
     * @mbggenerated
     */
    public Boolean getEnabled() {
        return enabled;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column brand.enabled
     *
     * @param enabled the value for brand.enabled
     *
     * @mbggenerated
     */
    public void setEnabled(Boolean enabled) {
        this.enabled = enabled;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column brand.status
     *
     * @return the value of brand.status
     *
     * @mbggenerated
     */
    public Byte getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column brand.status
     *
     * @param status the value for brand.status
     *
     * @mbggenerated
     */
    public void setStatus(Byte status) {
        this.status = status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column brand.vendor_application_id
     *
     * @return the value of brand.vendor_application_id
     *
     * @mbggenerated
     */
    public Long getVendorApplicationId() {
        return vendorApplicationId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column brand.vendor_application_id
     *
     * @param vendorApplicationId the value for brand.vendor_application_id
     *
     * @mbggenerated
     */
    public void setVendorApplicationId(Long vendorApplicationId) {
        this.vendorApplicationId = vendorApplicationId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column brand.hot_brand
     *
     * @return the value of brand.hot_brand
     *
     * @mbggenerated
     */
    public Integer getHotBrand() {
        return hotBrand;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column brand.hot_brand
     *
     * @param hotBrand the value for brand.hot_brand
     *
     * @mbggenerated
     */
    public void setHotBrand(Integer hotBrand) {
        this.hotBrand = hotBrand;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column brand.description
     *
     * @return the value of brand.description
     *
     * @mbggenerated
     */
    public String getDescription() {
        return description;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column brand.description
     *
     * @param description the value for brand.description
     *
     * @mbggenerated
     */
    public void setDescription(String description) {
        this.description = description == null ? null : description.trim();
    }
}