package com.intramirror.product.api.model;

import java.util.Date;

public class ContentTemplate {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column content_template.content_template_id
     *
     * @mbggenerated
     */
    private Long contentTemplateId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column content_template.template_name
     *
     * @mbggenerated
     */
    private String templateName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column content_template.status
     *
     * @mbggenerated
     */
    private Integer status;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column content_template.sort_num
     *
     * @mbggenerated
     */
    private Integer sortNum;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column content_template.created_at
     *
     * @mbggenerated
     */
    private Date createdAt;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column content_template.enabled
     *
     * @mbggenerated
     */
    private Boolean enabled;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column content_template.content
     *
     * @mbggenerated
     */
    private byte[] content;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column content_template.content_template_id
     *
     * @return the value of content_template.content_template_id
     *
     * @mbggenerated
     */
    public Long getContentTemplateId() {
        return contentTemplateId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column content_template.content_template_id
     *
     * @param contentTemplateId the value for content_template.content_template_id
     *
     * @mbggenerated
     */
    public void setContentTemplateId(Long contentTemplateId) {
        this.contentTemplateId = contentTemplateId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column content_template.template_name
     *
     * @return the value of content_template.template_name
     *
     * @mbggenerated
     */
    public String getTemplateName() {
        return templateName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column content_template.template_name
     *
     * @param templateName the value for content_template.template_name
     *
     * @mbggenerated
     */
    public void setTemplateName(String templateName) {
        this.templateName = templateName == null ? null : templateName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column content_template.status
     *
     * @return the value of content_template.status
     *
     * @mbggenerated
     */
    public Integer getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column content_template.status
     *
     * @param status the value for content_template.status
     *
     * @mbggenerated
     */
    public void setStatus(Integer status) {
        this.status = status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column content_template.sort_num
     *
     * @return the value of content_template.sort_num
     *
     * @mbggenerated
     */
    public Integer getSortNum() {
        return sortNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column content_template.sort_num
     *
     * @param sortNum the value for content_template.sort_num
     *
     * @mbggenerated
     */
    public void setSortNum(Integer sortNum) {
        this.sortNum = sortNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column content_template.created_at
     *
     * @return the value of content_template.created_at
     *
     * @mbggenerated
     */
    public Date getCreatedAt() {
        return createdAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column content_template.created_at
     *
     * @param createdAt the value for content_template.created_at
     *
     * @mbggenerated
     */
    public void setCreatedAt(Date createdAt) {
        this.createdAt = createdAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column content_template.enabled
     *
     * @return the value of content_template.enabled
     *
     * @mbggenerated
     */
    public Boolean getEnabled() {
        return enabled;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column content_template.enabled
     *
     * @param enabled the value for content_template.enabled
     *
     * @mbggenerated
     */
    public void setEnabled(Boolean enabled) {
        this.enabled = enabled;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column content_template.content
     *
     * @return the value of content_template.content
     *
     * @mbggenerated
     */
    public byte[] getContent() {
        return content;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column content_template.content
     *
     * @param content the value for content_template.content
     *
     * @mbggenerated
     */
    public void setContent(byte[] content) {
        this.content = content;
    }
}