package com.intramirror.product.api.model;

import java.util.Date;

public class ImPriceAlgorithm {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column im_price_algorithm.im_price_algorithm_id
     *
     * @mbggenerated
     */
    private Long imPriceAlgorithmId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column im_price_algorithm.category_type
     *
     * @mbggenerated
     */
    private Byte categoryType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column im_price_algorithm.season_code
     *
     * @mbggenerated
     */
    private String seasonCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column im_price_algorithm.name
     *
     * @mbggenerated
     */
    private String name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column im_price_algorithm.created_at
     *
     * @mbggenerated
     */
    private Date createdAt;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column im_price_algorithm.updated_at
     *
     * @mbggenerated
     */
    private Date updatedAt;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column im_price_algorithm.enabled
     *
     * @mbggenerated
     */
    private Boolean enabled;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column im_price_algorithm.im_price_algorithm_id
     *
     * @return the value of im_price_algorithm.im_price_algorithm_id
     *
     * @mbggenerated
     */
    public Long getImPriceAlgorithmId() {
        return imPriceAlgorithmId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column im_price_algorithm.im_price_algorithm_id
     *
     * @param imPriceAlgorithmId the value for im_price_algorithm.im_price_algorithm_id
     *
     * @mbggenerated
     */
    public void setImPriceAlgorithmId(Long imPriceAlgorithmId) {
        this.imPriceAlgorithmId = imPriceAlgorithmId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column im_price_algorithm.category_type
     *
     * @return the value of im_price_algorithm.category_type
     *
     * @mbggenerated
     */
    public Byte getCategoryType() {
        return categoryType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column im_price_algorithm.category_type
     *
     * @param categoryType the value for im_price_algorithm.category_type
     *
     * @mbggenerated
     */
    public void setCategoryType(Byte categoryType) {
        this.categoryType = categoryType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column im_price_algorithm.season_code
     *
     * @return the value of im_price_algorithm.season_code
     *
     * @mbggenerated
     */
    public String getSeasonCode() {
        return seasonCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column im_price_algorithm.season_code
     *
     * @param seasonCode the value for im_price_algorithm.season_code
     *
     * @mbggenerated
     */
    public void setSeasonCode(String seasonCode) {
        this.seasonCode = seasonCode == null ? null : seasonCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column im_price_algorithm.name
     *
     * @return the value of im_price_algorithm.name
     *
     * @mbggenerated
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column im_price_algorithm.name
     *
     * @param name the value for im_price_algorithm.name
     *
     * @mbggenerated
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column im_price_algorithm.created_at
     *
     * @return the value of im_price_algorithm.created_at
     *
     * @mbggenerated
     */
    public Date getCreatedAt() {
        return createdAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column im_price_algorithm.created_at
     *
     * @param createdAt the value for im_price_algorithm.created_at
     *
     * @mbggenerated
     */
    public void setCreatedAt(Date createdAt) {
        this.createdAt = createdAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column im_price_algorithm.updated_at
     *
     * @return the value of im_price_algorithm.updated_at
     *
     * @mbggenerated
     */
    public Date getUpdatedAt() {
        return updatedAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column im_price_algorithm.updated_at
     *
     * @param updatedAt the value for im_price_algorithm.updated_at
     *
     * @mbggenerated
     */
    public void setUpdatedAt(Date updatedAt) {
        this.updatedAt = updatedAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column im_price_algorithm.enabled
     *
     * @return the value of im_price_algorithm.enabled
     *
     * @mbggenerated
     */
    public Boolean getEnabled() {
        return enabled;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column im_price_algorithm.enabled
     *
     * @param enabled the value for im_price_algorithm.enabled
     *
     * @mbggenerated
     */
    public void setEnabled(Boolean enabled) {
        this.enabled = enabled;
    }
}