package com.intramirror.product.api.model;

public class ProductWithBLOBs extends Product {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product.cover_img
     *
     * @mbggenerated
     */
    private String coverImg;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product.description
     *
     * @mbggenerated
     */
    private String description;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product.description_img
     *
     * @mbggenerated
     */
    private String descriptionImg;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product.remark
     *
     * @mbggenerated
     */
    private String remark;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product.rejected_reason
     *
     * @mbggenerated
     */
    private String rejectedReason;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product.cover_img
     *
     * @return the value of product.cover_img
     *
     * @mbggenerated
     */
    public String getCoverImg() {
        return coverImg;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product.cover_img
     *
     * @param coverImg the value for product.cover_img
     *
     * @mbggenerated
     */
    public void setCoverImg(String coverImg) {
        this.coverImg = coverImg == null ? null : coverImg.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product.description
     *
     * @return the value of product.description
     *
     * @mbggenerated
     */
    public String getDescription() {
        return description;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product.description
     *
     * @param description the value for product.description
     *
     * @mbggenerated
     */
    public void setDescription(String description) {
        this.description = description == null ? null : description.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product.description_img
     *
     * @return the value of product.description_img
     *
     * @mbggenerated
     */
    public String getDescriptionImg() {
        return descriptionImg;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product.description_img
     *
     * @param descriptionImg the value for product.description_img
     *
     * @mbggenerated
     */
    public void setDescriptionImg(String descriptionImg) {
        this.descriptionImg = descriptionImg == null ? null : descriptionImg.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product.remark
     *
     * @return the value of product.remark
     *
     * @mbggenerated
     */
    public String getRemark() {
        return remark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product.remark
     *
     * @param remark the value for product.remark
     *
     * @mbggenerated
     */
    public void setRemark(String remark) {
        this.remark = remark == null ? null : remark.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product.rejected_reason
     *
     * @return the value of product.rejected_reason
     *
     * @mbggenerated
     */
    public String getRejectedReason() {
        return rejectedReason;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product.rejected_reason
     *
     * @param rejectedReason the value for product.rejected_reason
     *
     * @mbggenerated
     */
    public void setRejectedReason(String rejectedReason) {
        this.rejectedReason = rejectedReason == null ? null : rejectedReason.trim();
    }
}