package com.intramirror.product.api.model;

import java.util.Date;

public class Promotion {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_promotion.promotion_id
     *
     * @mbggenerated
     */
    private Long promotionId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_promotion.banner_id
     *
     * @mbggenerated
     */
    private Long bannerId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_promotion.promotion_name
     *
     * @mbggenerated
     */
    private String promotionName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_promotion.start_time
     *
     * @mbggenerated
     */
    private Date startTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_promotion.banner_img
     *
     * @mbggenerated
     */
    private String bannerImg;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_promotion.poster_img
     *
     * @mbggenerated
     */
    private String posterImg;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_promotion.created_at
     *
     * @mbggenerated
     */
    private Date createdAt;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_promotion.updated_at
     *
     * @mbggenerated
     */
    private Date updatedAt;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_promotion.enabled
     *
     * @mbggenerated
     */
    private Boolean enabled;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_promotion.description
     *
     * @mbggenerated
     */
    private String description;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_promotion.promotion_id
     *
     * @return the value of t_promotion.promotion_id
     *
     * @mbggenerated
     */
    public Long getPromotionId() {
        return promotionId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_promotion.promotion_id
     *
     * @param promotionId the value for t_promotion.promotion_id
     *
     * @mbggenerated
     */
    public void setPromotionId(Long promotionId) {
        this.promotionId = promotionId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_promotion.banner_id
     *
     * @return the value of t_promotion.banner_id
     *
     * @mbggenerated
     */
    public Long getBannerId() {
        return bannerId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_promotion.banner_id
     *
     * @param bannerId the value for t_promotion.banner_id
     *
     * @mbggenerated
     */
    public void setBannerId(Long bannerId) {
        this.bannerId = bannerId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_promotion.promotion_name
     *
     * @return the value of t_promotion.promotion_name
     *
     * @mbggenerated
     */
    public String getPromotionName() {
        return promotionName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_promotion.promotion_name
     *
     * @param promotionName the value for t_promotion.promotion_name
     *
     * @mbggenerated
     */
    public void setPromotionName(String promotionName) {
        this.promotionName = promotionName == null ? null : promotionName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_promotion.start_time
     *
     * @return the value of t_promotion.start_time
     *
     * @mbggenerated
     */
    public Date getStartTime() {
        return startTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_promotion.start_time
     *
     * @param startTime the value for t_promotion.start_time
     *
     * @mbggenerated
     */
    public void setStartTime(Date startTime) {
        this.startTime = startTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_promotion.banner_img
     *
     * @return the value of t_promotion.banner_img
     *
     * @mbggenerated
     */
    public String getBannerImg() {
        return bannerImg;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_promotion.banner_img
     *
     * @param bannerImg the value for t_promotion.banner_img
     *
     * @mbggenerated
     */
    public void setBannerImg(String bannerImg) {
        this.bannerImg = bannerImg == null ? null : bannerImg.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_promotion.poster_img
     *
     * @return the value of t_promotion.poster_img
     *
     * @mbggenerated
     */
    public String getPosterImg() {
        return posterImg;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_promotion.poster_img
     *
     * @param posterImg the value for t_promotion.poster_img
     *
     * @mbggenerated
     */
    public void setPosterImg(String posterImg) {
        this.posterImg = posterImg == null ? null : posterImg.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_promotion.created_at
     *
     * @return the value of t_promotion.created_at
     *
     * @mbggenerated
     */
    public Date getCreatedAt() {
        return createdAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_promotion.created_at
     *
     * @param createdAt the value for t_promotion.created_at
     *
     * @mbggenerated
     */
    public void setCreatedAt(Date createdAt) {
        this.createdAt = createdAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_promotion.updated_at
     *
     * @return the value of t_promotion.updated_at
     *
     * @mbggenerated
     */
    public Date getUpdatedAt() {
        return updatedAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_promotion.updated_at
     *
     * @param updatedAt the value for t_promotion.updated_at
     *
     * @mbggenerated
     */
    public void setUpdatedAt(Date updatedAt) {
        this.updatedAt = updatedAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_promotion.enabled
     *
     * @return the value of t_promotion.enabled
     *
     * @mbggenerated
     */
    public Boolean getEnabled() {
        return enabled;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_promotion.enabled
     *
     * @param enabled the value for t_promotion.enabled
     *
     * @mbggenerated
     */
    public void setEnabled(Boolean enabled) {
        this.enabled = enabled;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_promotion.description
     *
     * @return the value of t_promotion.description
     *
     * @mbggenerated
     */
    public String getDescription() {
        return description;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_promotion.description
     *
     * @param description the value for t_promotion.description
     *
     * @mbggenerated
     */
    public void setDescription(String description) {
        this.description = description == null ? null : description.trim();
    }
}