package com.intramirror.product.api.model;

public class PromotionBrandHot {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_promotion_brand_hot.promotion_brand_hot_id
     *
     * @mbggenerated
     */
    private Long promotionBrandHotId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_promotion_brand_hot.promotion_id
     *
     * @mbggenerated
     */
    private Long promotionId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_promotion_brand_hot.brand_id
     *
     * @mbggenerated
     */
    private Long brandId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_promotion_brand_hot.english_name
     *
     * @mbggenerated
     */
    private String englishName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_promotion_brand_hot.sort
     *
     * @mbggenerated
     */
    private Integer sort;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_promotion_brand_hot.promotion_brand_hot_id
     *
     * @return the value of t_promotion_brand_hot.promotion_brand_hot_id
     *
     * @mbggenerated
     */
    public Long getPromotionBrandHotId() {
        return promotionBrandHotId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_promotion_brand_hot.promotion_brand_hot_id
     *
     * @param promotionBrandHotId the value for t_promotion_brand_hot.promotion_brand_hot_id
     *
     * @mbggenerated
     */
    public void setPromotionBrandHotId(Long promotionBrandHotId) {
        this.promotionBrandHotId = promotionBrandHotId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_promotion_brand_hot.promotion_id
     *
     * @return the value of t_promotion_brand_hot.promotion_id
     *
     * @mbggenerated
     */
    public Long getPromotionId() {
        return promotionId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_promotion_brand_hot.promotion_id
     *
     * @param promotionId the value for t_promotion_brand_hot.promotion_id
     *
     * @mbggenerated
     */
    public void setPromotionId(Long promotionId) {
        this.promotionId = promotionId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_promotion_brand_hot.brand_id
     *
     * @return the value of t_promotion_brand_hot.brand_id
     *
     * @mbggenerated
     */
    public Long getBrandId() {
        return brandId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_promotion_brand_hot.brand_id
     *
     * @param brandId the value for t_promotion_brand_hot.brand_id
     *
     * @mbggenerated
     */
    public void setBrandId(Long brandId) {
        this.brandId = brandId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_promotion_brand_hot.english_name
     *
     * @return the value of t_promotion_brand_hot.english_name
     *
     * @mbggenerated
     */
    public String getEnglishName() {
        return englishName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_promotion_brand_hot.english_name
     *
     * @param englishName the value for t_promotion_brand_hot.english_name
     *
     * @mbggenerated
     */
    public void setEnglishName(String englishName) {
        this.englishName = englishName == null ? null : englishName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_promotion_brand_hot.sort
     *
     * @return the value of t_promotion_brand_hot.sort
     *
     * @mbggenerated
     */
    public Integer getSort() {
        return sort;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_promotion_brand_hot.sort
     *
     * @param sort the value for t_promotion_brand_hot.sort
     *
     * @mbggenerated
     */
    public void setSort(Integer sort) {
        this.sort = sort;
    }
}