package com.intramirror.product.api.model;

import java.math.BigDecimal;
import java.util.Date;

public class Shop {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column shop.shop_id
     *
     * @mbggenerated
     */
    private Long shopId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column shop.shop_name
     *
     * @mbggenerated
     */
    private String shopName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column shop.shop_pic
     *
     * @mbggenerated
     */
    private String shopPic;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column shop.service_rating
     *
     * @mbggenerated
     */
    private BigDecimal serviceRating;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column shop.user_id
     *
     * @mbggenerated
     */
    private Long userId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column shop.type
     *
     * @mbggenerated
     */
    private Byte type;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column shop.shop_organization_application_id
     *
     * @mbggenerated
     */
    private Long shopOrganizationApplicationId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column shop.shop_individual_application_id
     *
     * @mbggenerated
     */
    private Long shopIndividualApplicationId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column shop.shop_brand_type
     *
     * @mbggenerated
     */
    private Byte shopBrandType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column shop.status
     *
     * @mbggenerated
     */
    private Byte status;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column shop.identity_card
     *
     * @mbggenerated
     */
    private String identityCard;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column shop.company_bank_account
     *
     * @mbggenerated
     */
    private String companyBankAccount;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column shop.company_name
     *
     * @mbggenerated
     */
    private String companyName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column shop.registered_person
     *
     * @mbggenerated
     */
    private String registeredPerson;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column shop.electronic_identification_card
     *
     * @mbggenerated
     */
    private String electronicIdentificationCard;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column shop.business_license_number
     *
     * @mbggenerated
     */
    private String businessLicenseNumber;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column shop.business_license_duration
     *
     * @mbggenerated
     */
    private Date businessLicenseDuration;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column shop.electronic_business_license
     *
     * @mbggenerated
     */
    private String electronicBusinessLicense;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column shop.legal_management_scope
     *
     * @mbggenerated
     */
    private String legalManagementScope;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column shop.business_license_location
     *
     * @mbggenerated
     */
    private String businessLicenseLocation;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column shop.created_at
     *
     * @mbggenerated
     */
    private Date createdAt;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column shop.updated_at
     *
     * @mbggenerated
     */
    private Date updatedAt;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column shop.enabled
     *
     * @mbggenerated
     */
    private Boolean enabled;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column shop.returned_rate
     *
     * @mbggenerated
     */
    private BigDecimal returnedRate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column shop.balance
     *
     * @mbggenerated
     */
    private BigDecimal balance;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column shop.given_balance
     *
     * @mbggenerated
     */
    private BigDecimal givenBalance;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column shop.revenue
     *
     * @mbggenerated
     */
    private BigDecimal revenue;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column shop.banner_pic
     *
     * @mbggenerated
     */
    private String bannerPic;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column shop.banner_shop_product_ids
     *
     * @mbggenerated
     */
    private String bannerShopProductIds;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column shop.grade
     *
     * @mbggenerated
     */
    private Byte grade;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column shop.contact_person_name
     *
     * @mbggenerated
     */
    private String contactPersonName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column shop.score
     *
     * @mbggenerated
     */
    private BigDecimal score;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column shop.introduction
     *
     * @mbggenerated
     */
    private String introduction;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column shop.shop_id
     *
     * @return the value of shop.shop_id
     *
     * @mbggenerated
     */
    public Long getShopId() {
        return shopId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column shop.shop_id
     *
     * @param shopId the value for shop.shop_id
     *
     * @mbggenerated
     */
    public void setShopId(Long shopId) {
        this.shopId = shopId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column shop.shop_name
     *
     * @return the value of shop.shop_name
     *
     * @mbggenerated
     */
    public String getShopName() {
        return shopName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column shop.shop_name
     *
     * @param shopName the value for shop.shop_name
     *
     * @mbggenerated
     */
    public void setShopName(String shopName) {
        this.shopName = shopName == null ? null : shopName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column shop.shop_pic
     *
     * @return the value of shop.shop_pic
     *
     * @mbggenerated
     */
    public String getShopPic() {
        return shopPic;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column shop.shop_pic
     *
     * @param shopPic the value for shop.shop_pic
     *
     * @mbggenerated
     */
    public void setShopPic(String shopPic) {
        this.shopPic = shopPic == null ? null : shopPic.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column shop.service_rating
     *
     * @return the value of shop.service_rating
     *
     * @mbggenerated
     */
    public BigDecimal getServiceRating() {
        return serviceRating;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column shop.service_rating
     *
     * @param serviceRating the value for shop.service_rating
     *
     * @mbggenerated
     */
    public void setServiceRating(BigDecimal serviceRating) {
        this.serviceRating = serviceRating;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column shop.user_id
     *
     * @return the value of shop.user_id
     *
     * @mbggenerated
     */
    public Long getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column shop.user_id
     *
     * @param userId the value for shop.user_id
     *
     * @mbggenerated
     */
    public void setUserId(Long userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column shop.type
     *
     * @return the value of shop.type
     *
     * @mbggenerated
     */
    public Byte getType() {
        return type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column shop.type
     *
     * @param type the value for shop.type
     *
     * @mbggenerated
     */
    public void setType(Byte type) {
        this.type = type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column shop.shop_organization_application_id
     *
     * @return the value of shop.shop_organization_application_id
     *
     * @mbggenerated
     */
    public Long getShopOrganizationApplicationId() {
        return shopOrganizationApplicationId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column shop.shop_organization_application_id
     *
     * @param shopOrganizationApplicationId the value for shop.shop_organization_application_id
     *
     * @mbggenerated
     */
    public void setShopOrganizationApplicationId(Long shopOrganizationApplicationId) {
        this.shopOrganizationApplicationId = shopOrganizationApplicationId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column shop.shop_individual_application_id
     *
     * @return the value of shop.shop_individual_application_id
     *
     * @mbggenerated
     */
    public Long getShopIndividualApplicationId() {
        return shopIndividualApplicationId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column shop.shop_individual_application_id
     *
     * @param shopIndividualApplicationId the value for shop.shop_individual_application_id
     *
     * @mbggenerated
     */
    public void setShopIndividualApplicationId(Long shopIndividualApplicationId) {
        this.shopIndividualApplicationId = shopIndividualApplicationId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column shop.shop_brand_type
     *
     * @return the value of shop.shop_brand_type
     *
     * @mbggenerated
     */
    public Byte getShopBrandType() {
        return shopBrandType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column shop.shop_brand_type
     *
     * @param shopBrandType the value for shop.shop_brand_type
     *
     * @mbggenerated
     */
    public void setShopBrandType(Byte shopBrandType) {
        this.shopBrandType = shopBrandType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column shop.status
     *
     * @return the value of shop.status
     *
     * @mbggenerated
     */
    public Byte getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column shop.status
     *
     * @param status the value for shop.status
     *
     * @mbggenerated
     */
    public void setStatus(Byte status) {
        this.status = status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column shop.identity_card
     *
     * @return the value of shop.identity_card
     *
     * @mbggenerated
     */
    public String getIdentityCard() {
        return identityCard;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column shop.identity_card
     *
     * @param identityCard the value for shop.identity_card
     *
     * @mbggenerated
     */
    public void setIdentityCard(String identityCard) {
        this.identityCard = identityCard == null ? null : identityCard.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column shop.company_bank_account
     *
     * @return the value of shop.company_bank_account
     *
     * @mbggenerated
     */
    public String getCompanyBankAccount() {
        return companyBankAccount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column shop.company_bank_account
     *
     * @param companyBankAccount the value for shop.company_bank_account
     *
     * @mbggenerated
     */
    public void setCompanyBankAccount(String companyBankAccount) {
        this.companyBankAccount = companyBankAccount == null ? null : companyBankAccount.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column shop.company_name
     *
     * @return the value of shop.company_name
     *
     * @mbggenerated
     */
    public String getCompanyName() {
        return companyName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column shop.company_name
     *
     * @param companyName the value for shop.company_name
     *
     * @mbggenerated
     */
    public void setCompanyName(String companyName) {
        this.companyName = companyName == null ? null : companyName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column shop.registered_person
     *
     * @return the value of shop.registered_person
     *
     * @mbggenerated
     */
    public String getRegisteredPerson() {
        return registeredPerson;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column shop.registered_person
     *
     * @param registeredPerson the value for shop.registered_person
     *
     * @mbggenerated
     */
    public void setRegisteredPerson(String registeredPerson) {
        this.registeredPerson = registeredPerson == null ? null : registeredPerson.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column shop.electronic_identification_card
     *
     * @return the value of shop.electronic_identification_card
     *
     * @mbggenerated
     */
    public String getElectronicIdentificationCard() {
        return electronicIdentificationCard;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column shop.electronic_identification_card
     *
     * @param electronicIdentificationCard the value for shop.electronic_identification_card
     *
     * @mbggenerated
     */
    public void setElectronicIdentificationCard(String electronicIdentificationCard) {
        this.electronicIdentificationCard = electronicIdentificationCard == null ? null : electronicIdentificationCard.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column shop.business_license_number
     *
     * @return the value of shop.business_license_number
     *
     * @mbggenerated
     */
    public String getBusinessLicenseNumber() {
        return businessLicenseNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column shop.business_license_number
     *
     * @param businessLicenseNumber the value for shop.business_license_number
     *
     * @mbggenerated
     */
    public void setBusinessLicenseNumber(String businessLicenseNumber) {
        this.businessLicenseNumber = businessLicenseNumber == null ? null : businessLicenseNumber.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column shop.business_license_duration
     *
     * @return the value of shop.business_license_duration
     *
     * @mbggenerated
     */
    public Date getBusinessLicenseDuration() {
        return businessLicenseDuration;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column shop.business_license_duration
     *
     * @param businessLicenseDuration the value for shop.business_license_duration
     *
     * @mbggenerated
     */
    public void setBusinessLicenseDuration(Date businessLicenseDuration) {
        this.businessLicenseDuration = businessLicenseDuration;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column shop.electronic_business_license
     *
     * @return the value of shop.electronic_business_license
     *
     * @mbggenerated
     */
    public String getElectronicBusinessLicense() {
        return electronicBusinessLicense;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column shop.electronic_business_license
     *
     * @param electronicBusinessLicense the value for shop.electronic_business_license
     *
     * @mbggenerated
     */
    public void setElectronicBusinessLicense(String electronicBusinessLicense) {
        this.electronicBusinessLicense = electronicBusinessLicense == null ? null : electronicBusinessLicense.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column shop.legal_management_scope
     *
     * @return the value of shop.legal_management_scope
     *
     * @mbggenerated
     */
    public String getLegalManagementScope() {
        return legalManagementScope;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column shop.legal_management_scope
     *
     * @param legalManagementScope the value for shop.legal_management_scope
     *
     * @mbggenerated
     */
    public void setLegalManagementScope(String legalManagementScope) {
        this.legalManagementScope = legalManagementScope == null ? null : legalManagementScope.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column shop.business_license_location
     *
     * @return the value of shop.business_license_location
     *
     * @mbggenerated
     */
    public String getBusinessLicenseLocation() {
        return businessLicenseLocation;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column shop.business_license_location
     *
     * @param businessLicenseLocation the value for shop.business_license_location
     *
     * @mbggenerated
     */
    public void setBusinessLicenseLocation(String businessLicenseLocation) {
        this.businessLicenseLocation = businessLicenseLocation == null ? null : businessLicenseLocation.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column shop.created_at
     *
     * @return the value of shop.created_at
     *
     * @mbggenerated
     */
    public Date getCreatedAt() {
        return createdAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column shop.created_at
     *
     * @param createdAt the value for shop.created_at
     *
     * @mbggenerated
     */
    public void setCreatedAt(Date createdAt) {
        this.createdAt = createdAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column shop.updated_at
     *
     * @return the value of shop.updated_at
     *
     * @mbggenerated
     */
    public Date getUpdatedAt() {
        return updatedAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column shop.updated_at
     *
     * @param updatedAt the value for shop.updated_at
     *
     * @mbggenerated
     */
    public void setUpdatedAt(Date updatedAt) {
        this.updatedAt = updatedAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column shop.enabled
     *
     * @return the value of shop.enabled
     *
     * @mbggenerated
     */
    public Boolean getEnabled() {
        return enabled;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column shop.enabled
     *
     * @param enabled the value for shop.enabled
     *
     * @mbggenerated
     */
    public void setEnabled(Boolean enabled) {
        this.enabled = enabled;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column shop.returned_rate
     *
     * @return the value of shop.returned_rate
     *
     * @mbggenerated
     */
    public BigDecimal getReturnedRate() {
        return returnedRate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column shop.returned_rate
     *
     * @param returnedRate the value for shop.returned_rate
     *
     * @mbggenerated
     */
    public void setReturnedRate(BigDecimal returnedRate) {
        this.returnedRate = returnedRate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column shop.balance
     *
     * @return the value of shop.balance
     *
     * @mbggenerated
     */
    public BigDecimal getBalance() {
        return balance;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column shop.balance
     *
     * @param balance the value for shop.balance
     *
     * @mbggenerated
     */
    public void setBalance(BigDecimal balance) {
        this.balance = balance;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column shop.given_balance
     *
     * @return the value of shop.given_balance
     *
     * @mbggenerated
     */
    public BigDecimal getGivenBalance() {
        return givenBalance;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column shop.given_balance
     *
     * @param givenBalance the value for shop.given_balance
     *
     * @mbggenerated
     */
    public void setGivenBalance(BigDecimal givenBalance) {
        this.givenBalance = givenBalance;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column shop.revenue
     *
     * @return the value of shop.revenue
     *
     * @mbggenerated
     */
    public BigDecimal getRevenue() {
        return revenue;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column shop.revenue
     *
     * @param revenue the value for shop.revenue
     *
     * @mbggenerated
     */
    public void setRevenue(BigDecimal revenue) {
        this.revenue = revenue;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column shop.banner_pic
     *
     * @return the value of shop.banner_pic
     *
     * @mbggenerated
     */
    public String getBannerPic() {
        return bannerPic;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column shop.banner_pic
     *
     * @param bannerPic the value for shop.banner_pic
     *
     * @mbggenerated
     */
    public void setBannerPic(String bannerPic) {
        this.bannerPic = bannerPic == null ? null : bannerPic.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column shop.banner_shop_product_ids
     *
     * @return the value of shop.banner_shop_product_ids
     *
     * @mbggenerated
     */
    public String getBannerShopProductIds() {
        return bannerShopProductIds;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column shop.banner_shop_product_ids
     *
     * @param bannerShopProductIds the value for shop.banner_shop_product_ids
     *
     * @mbggenerated
     */
    public void setBannerShopProductIds(String bannerShopProductIds) {
        this.bannerShopProductIds = bannerShopProductIds == null ? null : bannerShopProductIds.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column shop.grade
     *
     * @return the value of shop.grade
     *
     * @mbggenerated
     */
    public Byte getGrade() {
        return grade;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column shop.grade
     *
     * @param grade the value for shop.grade
     *
     * @mbggenerated
     */
    public void setGrade(Byte grade) {
        this.grade = grade;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column shop.contact_person_name
     *
     * @return the value of shop.contact_person_name
     *
     * @mbggenerated
     */
    public String getContactPersonName() {
        return contactPersonName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column shop.contact_person_name
     *
     * @param contactPersonName the value for shop.contact_person_name
     *
     * @mbggenerated
     */
    public void setContactPersonName(String contactPersonName) {
        this.contactPersonName = contactPersonName == null ? null : contactPersonName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column shop.score
     *
     * @return the value of shop.score
     *
     * @mbggenerated
     */
    public BigDecimal getScore() {
        return score;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column shop.score
     *
     * @param score the value for shop.score
     *
     * @mbggenerated
     */
    public void setScore(BigDecimal score) {
        this.score = score;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column shop.introduction
     *
     * @return the value of shop.introduction
     *
     * @mbggenerated
     */
    public String getIntroduction() {
        return introduction;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column shop.introduction
     *
     * @param introduction the value for shop.introduction
     *
     * @mbggenerated
     */
    public void setIntroduction(String introduction) {
        this.introduction = introduction == null ? null : introduction.trim();
    }
}