package com.intramirror.product.api.model;

import java.util.Date;

public class SnapshotPriceRule {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column snapshot_price_rule.snapshot_price_rule_id
     *
     * @mbggenerated
     */
    private Long snapshotPriceRuleId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column snapshot_price_rule.price_change_rule_id
     *
     * @mbggenerated
     */
    private Long priceChangeRuleId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column snapshot_price_rule.save_at
     *
     * @mbggenerated
     */
    private Date saveAt;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column snapshot_price_rule.updated_at
     *
     * @mbggenerated
     */
    private Date updatedAt;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column snapshot_price_rule.status
     *
     * @mbggenerated
     */
    private Byte status;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column snapshot_price_rule.valid_from
     *
     * @mbggenerated
     */
    private Date validFrom;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column snapshot_price_rule.created_at
     *
     * @mbggenerated
     */
    private Date createdAt;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column snapshot_price_rule.enabled
     *
     * @mbggenerated
     */
    private Boolean enabled;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column snapshot_price_rule.snapshot_price_rule_id
     *
     * @return the value of snapshot_price_rule.snapshot_price_rule_id
     *
     * @mbggenerated
     */
    public Long getSnapshotPriceRuleId() {
        return snapshotPriceRuleId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column snapshot_price_rule.snapshot_price_rule_id
     *
     * @param snapshotPriceRuleId the value for snapshot_price_rule.snapshot_price_rule_id
     *
     * @mbggenerated
     */
    public void setSnapshotPriceRuleId(Long snapshotPriceRuleId) {
        this.snapshotPriceRuleId = snapshotPriceRuleId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column snapshot_price_rule.price_change_rule_id
     *
     * @return the value of snapshot_price_rule.price_change_rule_id
     *
     * @mbggenerated
     */
    public Long getPriceChangeRuleId() {
        return priceChangeRuleId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column snapshot_price_rule.price_change_rule_id
     *
     * @param priceChangeRuleId the value for snapshot_price_rule.price_change_rule_id
     *
     * @mbggenerated
     */
    public void setPriceChangeRuleId(Long priceChangeRuleId) {
        this.priceChangeRuleId = priceChangeRuleId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column snapshot_price_rule.save_at
     *
     * @return the value of snapshot_price_rule.save_at
     *
     * @mbggenerated
     */
    public Date getSaveAt() {
        return saveAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column snapshot_price_rule.save_at
     *
     * @param saveAt the value for snapshot_price_rule.save_at
     *
     * @mbggenerated
     */
    public void setSaveAt(Date saveAt) {
        this.saveAt = saveAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column snapshot_price_rule.updated_at
     *
     * @return the value of snapshot_price_rule.updated_at
     *
     * @mbggenerated
     */
    public Date getUpdatedAt() {
        return updatedAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column snapshot_price_rule.updated_at
     *
     * @param updatedAt the value for snapshot_price_rule.updated_at
     *
     * @mbggenerated
     */
    public void setUpdatedAt(Date updatedAt) {
        this.updatedAt = updatedAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column snapshot_price_rule.status
     *
     * @return the value of snapshot_price_rule.status
     *
     * @mbggenerated
     */
    public Byte getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column snapshot_price_rule.status
     *
     * @param status the value for snapshot_price_rule.status
     *
     * @mbggenerated
     */
    public void setStatus(Byte status) {
        this.status = status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column snapshot_price_rule.valid_from
     *
     * @return the value of snapshot_price_rule.valid_from
     *
     * @mbggenerated
     */
    public Date getValidFrom() {
        return validFrom;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column snapshot_price_rule.valid_from
     *
     * @param validFrom the value for snapshot_price_rule.valid_from
     *
     * @mbggenerated
     */
    public void setValidFrom(Date validFrom) {
        this.validFrom = validFrom;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column snapshot_price_rule.created_at
     *
     * @return the value of snapshot_price_rule.created_at
     *
     * @mbggenerated
     */
    public Date getCreatedAt() {
        return createdAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column snapshot_price_rule.created_at
     *
     * @param createdAt the value for snapshot_price_rule.created_at
     *
     * @mbggenerated
     */
    public void setCreatedAt(Date createdAt) {
        this.createdAt = createdAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column snapshot_price_rule.enabled
     *
     * @return the value of snapshot_price_rule.enabled
     *
     * @mbggenerated
     */
    public Boolean getEnabled() {
        return enabled;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column snapshot_price_rule.enabled
     *
     * @param enabled the value for snapshot_price_rule.enabled
     *
     * @mbggenerated
     */
    public void setEnabled(Boolean enabled) {
        this.enabled = enabled;
    }
}