package com.intramirror.order.core.mapper;

import com.intramirror.order.api.model.CczhangOrderEmail;

public interface CczhangOrderEmailMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cczhang_order_email
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cczhang_order_email
     *
     * @mbggenerated
     */
    int insert(CczhangOrderEmail record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cczhang_order_email
     *
     * @mbggenerated
     */
    int insertSelective(CczhangOrderEmail record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cczhang_order_email
     *
     * @mbggenerated
     */
    CczhangOrderEmail selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cczhang_order_email
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(CczhangOrderEmail record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cczhang_order_email
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(CczhangOrderEmail record);
}