package com.intramirror.order.core.mapper;

import com.intramirror.order.api.model.Logistics;

public interface LogisticsMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table logistics
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Long logisticsId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table logistics
     *
     * @mbggenerated
     */
    int insert(Logistics record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table logistics
     *
     * @mbggenerated
     */
    int insertSelective(Logistics record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table logistics
     *
     * @mbggenerated
     */
    Logistics selectByPrimaryKey(Long logisticsId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table logistics
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(Logistics record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table logistics
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(Logistics record);
}