package com.intramirror.order.core.mapper;

import com.intramirror.order.api.model.ShippingProvider;

import java.util.List;

public interface ShippingProviderMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table shipping_provider
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Long shippingProviderId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table shipping_provider
     *
     * @mbggenerated
     */
    int insert(ShippingProvider record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table shipping_provider
     *
     * @mbggenerated
     */
    int insertSelective(ShippingProvider record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table shipping_provider
     *
     * @mbggenerated
     */
    ShippingProvider selectByPrimaryKey(Long shippingProviderId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table shipping_provider
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(ShippingProvider record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table shipping_provider
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(ShippingProvider record);

    List<ShippingProvider> getShippingProviderByShipmentId(Long shipmentId);

    List<ShippingProvider> getShippingProviderByName(String name);

    ShippingProvider getShippingProviderByVendorId(Long venodrId);
}