package com.intramirror.product.core.mapper;

import com.intramirror.product.api.model.ApiErrorProcessing;

public interface ApiErrorProcessingMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table api_error_processing
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Long apiErrorProcessingId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table api_error_processing
     *
     * @mbggenerated
     */
    int insert(ApiErrorProcessing record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table api_error_processing
     *
     * @mbggenerated
     */
    int insertSelective(ApiErrorProcessing record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table api_error_processing
     *
     * @mbggenerated
     */
    ApiErrorProcessing selectByPrimaryKey(Long apiErrorProcessingId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table api_error_processing
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(ApiErrorProcessing record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table api_error_processing
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(ApiErrorProcessing record);
}