package com.intramirror.product.core.mapper;

import com.intramirror.product.api.model.ContentTemplate;

public interface ContentTemplateMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table content_template
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Long contentTemplateId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table content_template
     *
     * @mbggenerated
     */
    int insert(ContentTemplate record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table content_template
     *
     * @mbggenerated
     */
    int insertSelective(ContentTemplate record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table content_template
     *
     * @mbggenerated
     */
    ContentTemplate selectByPrimaryKey(Long contentTemplateId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table content_template
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(ContentTemplate record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table content_template
     *
     * @mbggenerated
     */
    int updateByPrimaryKeyWithBLOBs(ContentTemplate record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table content_template
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(ContentTemplate record);
}