package com.intramirror.product.core.mapper;

import com.intramirror.product.api.model.ImPriceAlgorithm;

import java.util.List;
import java.util.Map;

public interface ImPriceAlgorithmMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table im_price_algorithm
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Long imPriceAlgorithmId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table im_price_algorithm
     *
     * @mbggenerated
     */
    int insert(ImPriceAlgorithm record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table im_price_algorithm
     *
     * @mbggenerated
     */
    int insertSelective(ImPriceAlgorithm record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table im_price_algorithm
     *
     * @mbggenerated
     */
    ImPriceAlgorithm selectByPrimaryKey(Long imPriceAlgorithmId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table im_price_algorithm
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(ImPriceAlgorithm record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table im_price_algorithm
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(ImPriceAlgorithm record);

    List<ImPriceAlgorithm> selectByParams(Map<String, Object> params);
}