package com.intramirror.product.core.mapper;

import com.intramirror.product.api.model.PriceChangeRuleProduct;

import org.apache.ibatis.annotations.Param;

import java.util.List;

public interface PriceChangeRuleProductMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table price_change_rule_product
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Long priceChangeRuleProductId);
    
    
    /**
     * 根据priceChangeRuleId  删除
     * @param priceChangeRuleId
     * @return
     */
    int deleteBypriceChangeRuleId(Long priceChangeRuleId);
    
    

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table price_change_rule_product
     *
     * @mbggenerated
     */
    int insert(PriceChangeRuleProduct record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table price_change_rule_product
     *
     * @mbggenerated
     */
    int insertSelective(PriceChangeRuleProduct record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table price_change_rule_product
     *
     * @mbggenerated
     */
    PriceChangeRuleProduct selectByPrimaryKey(Long priceChangeRuleProductId);
    
    
    /**
     * 根据priceChangeRuleId 查询
     * @param priceChangeRuleId
     * @return
     */
    List<PriceChangeRuleProduct> selectByPriceChangeRuleId(Long priceChangeRuleId);
    

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table price_change_rule_product
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(PriceChangeRuleProduct record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table price_change_rule_product
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(PriceChangeRuleProduct record);

    List<PriceChangeRuleProduct> getPriceChangeRuleGroupListByPriceChangeRuleId(@Param("priceChangeRuleId") Long priceChangeRuleId);
}