package com.intramirror.product.core.mapper;

import com.intramirror.product.api.model.PriceChangeRuleCategoryBrand;

import org.apache.ibatis.annotations.Param;

import java.util.List;
import java.util.Map;

public interface PriceChangeRuleCategoryBrandMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table price_change_rule_category_brand
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Long priceChangeRuleCategoryBrandId);
    
    /**
     *根据条件删除 PriceChangeRuleCategoryBrand
     * @mbggenerated
     */
    int deleteByParameter(PriceChangeRuleCategoryBrand record);
    
    /**
     * 根据priceChangeRuleId 删除
     * @param priceChangeRuleId
     * @return
     */
    int deleteByPriceChangeRuleId(Long priceChangeRuleId);
    

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table price_change_rule_category_brand
     *
     * @mbggenerated
     */
    int insert(PriceChangeRuleCategoryBrand record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table price_change_rule_category_brand
     *
     * @mbggenerated
     */
    Long insertSelective(PriceChangeRuleCategoryBrand record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table price_change_rule_category_brand
     *
     * @mbggenerated
     */
    PriceChangeRuleCategoryBrand selectByPrimaryKey(Long priceChangeRuleCategoryBrandId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table price_change_rule_category_brand
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(PriceChangeRuleCategoryBrand record);


    /**
     * 根据parameter 修改折扣信息
     *
     * @mbggenerated
     */
    int updateDiscountPercentageBySelective(PriceChangeRuleCategoryBrand record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table price_change_rule_category_brand
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(PriceChangeRuleCategoryBrand record);

    List<Map<String,Object>> selectPriceChangeRuleCategoryBrandExists(Map<String,Object> map);
    List<PriceChangeRuleCategoryBrand> getPriceChangeRuleGroupListByPriceChangeRuleIdAndExceptionFlag(@Param("priceChangeRuleId") Long priceChangeRuleId, @Param("exceptionFlag") Integer exceptionFlag);
}