package com.intramirror.product.core.mapper;

import com.intramirror.product.api.model.ShopProduct;
import com.intramirror.product.api.model.ShopProductWithBLOBs;

public interface ShopProductMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table shop_product
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Long shopProductId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table shop_product
     *
     * @mbggenerated
     */
    int insert(ShopProductWithBLOBs record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table shop_product
     *
     * @mbggenerated
     */
    int insertSelective(ShopProductWithBLOBs record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table shop_product
     *
     * @mbggenerated
     */
    ShopProductWithBLOBs selectByPrimaryKey(Long shopProductId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table shop_product
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(ShopProductWithBLOBs record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table shop_product
     *
     * @mbggenerated
     */
    int updateByPrimaryKeyWithBLOBs(ShopProductWithBLOBs record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table shop_product
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(ShopProduct record);

    int updateShopProductByProductId(ShopProduct record);
}