package com.intramirror.product.core.mapper;

import com.intramirror.product.api.model.TagProductRel;

public interface TagProductRelMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tag_product_rel
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Long tagProductId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tag_product_rel
     *
     * @mbggenerated
     */
    int insert(TagProductRel record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tag_product_rel
     *
     * @mbggenerated
     */
    int insertSelective(TagProductRel record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tag_product_rel
     *
     * @mbggenerated
     */
    TagProductRel selectByPrimaryKey(Long tagProductId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tag_product_rel
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(TagProductRel record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tag_product_rel
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(TagProductRel record);
}