package com.intramirror.user.core.mapper;

import com.intramirror.user.api.model.UserApiMq;

public interface UserApiMqMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table api_mq
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Long apiMqId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table api_mq
     *
     * @mbggenerated
     */
    int insert(UserApiMq record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table api_mq
     *
     * @mbggenerated
     */
    int insertSelective(UserApiMq record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table api_mq
     *
     * @mbggenerated
     */
    UserApiMq selectByPrimaryKey(Long apiMqId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table api_mq
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(UserApiMq record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table api_mq
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(UserApiMq record);
}