ALTER TABLE block ADD text_color CHAR(32) NULL;
ALTER TABLE block
  MODIFY COLUMN text_color CHAR(32) AFTER content;
ALTER TABLE `block`
	CHANGE COLUMN `modified_at` `modified_at` TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP;